// frontend-react/src/pages/admin/SubscriptionDetail.tsx
import React, { useEffect, useState, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { ArrowLeft, Plus, Settings, RotateCw, Copy, Edit2, Eye } from 'lucide-react'
import request from '@/utils/request'
import { useToast } from '@/components/ui/ToastProvider'

interface SubscriptionInfo {
  id: number
  package_name: string
  package_code: string
  endpoint?: string
  price: number
  credits: number
  duration_days: number
  sort_order: number
  created_at: string
  description?: string
  is_active: boolean
}

interface UserKey {
  id: number
  user_id: number
  api_key_id: number
  api_key: string
  real_api_key?: string
  user_email: string
  status: string
  activation_date?: string
  expire_date?: string
  remaining_days: number
  remaining_credits: number
  total_credits: number
  last_used_at?: string
  notes?: string
}

const SubscriptionDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const { success, error } = useToast()

  const [subscription, setSubscription] = useState<SubscriptionInfo | null>(null)
  const [userKeys, setUserKeys] = useState<UserKey[]>([])
  const [selectedKeys, setSelectedKeys] = useState<UserKey[]>([])
  const [statusFilter, setStatusFilter] = useState<string>('')

  const [loadingDetail, setLoadingDetail] = useState(false)
  const [loadingUserKeys, setLoadingUserKeys] = useState(false)
  const [loadingBatchGenerate, setLoadingBatchGenerate] = useState(false)
  const [loadingBulkOperation, setLoadingBulkOperation] = useState(false)

  const [pagination, setPagination] = useState({
    page: 1,
    size: 25,
    total: 0,
  })

  const [bulkOperationDialog, setBulkOperationDialog] = useState(false)
  const [bulkOperation, setBulkOperation] = useState({
    operation: '',
    notes: '',
  })

  const [editingKeyId, setEditingKeyId] = useState<number | null>(null)
  const [editingValue, setEditingValue] = useState('')
  const editInputRef = useRef<HTMLInputElement>(null)

  const loadSubscriptionDetail = async () => {
    if (!id) return
    try {
      setLoadingDetail(true)
      console.log('Loading subscription detail for ID:', id)
      const res: any = await request.get(`/packages/${id}`)
      console.log('Subscription detail response:', res)
      setSubscription(res || null)
    } catch (err) {
      console.error('failed to load subscription detail', err)
    } finally {
      setLoadingDetail(false)
    }
  }

  const loadUserKeys = async () => {
    if (!id) return
    try {
      setLoadingUserKeys(true)
      console.log('Loading user keys for subscription ID:', id)
      const res: any = await request.get(`/packages/${id}/userkeys`, {
        params: {
          page: pagination.page,
          page_size: pagination.size,
          status_filter: statusFilter || undefined,
        }
      })
      console.log('User keys response:', res)
      setUserKeys(res.user_keys || [])
      setPagination(prev => ({ ...prev, total: res.total || 0 }))
    } catch (err) {
      console.error('failed to load user keys', err)
    } finally {
      setLoadingUserKeys(false)
    }
  }

  useEffect(() => {
    loadSubscriptionDetail()
    loadUserKeys()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id, pagination.page, pagination.size, statusFilter])

  const handleBatchGenerate = async () => {
    if (!id) return
    try {
      setLoadingBatchGenerate(true)
      await request.post(`/packages/${id}/userkeys/batch-generate`, {
        count: 10,
        status: 'inactive'
      })
      success('批量生成用户密钥成功')
      setPagination(prev => ({ ...prev, page: 1 }))
      loadUserKeys()
    } catch (err) {
      console.error('failed to batch generate', err)
      error('批量生成失败')
    } finally {
      setLoadingBatchGenerate(false)
    }
  }

  const handleBulkOperation = async () => {
    if (!id || !bulkOperation.operation) return
    try {
      setLoadingBulkOperation(true)
      await request.post(`/packages/${id}/userkeys/batch`, {
        user_ids: selectedKeys.map(k => k.user_id),
        api_key_id: selectedKeys[0]?.api_key_id,
        operation: bulkOperation.operation,
        notes: bulkOperation.notes,
      })
      success('批量操作成功')
      setBulkOperationDialog(false)
      setBulkOperation({ operation: '', notes: '' })
      setSelectedKeys([])
      loadUserKeys()
    } catch (err) {
      console.error('failed to execute bulk operation', err)
      error('批量操作失败')
    } finally {
      setLoadingBulkOperation(false)
    }
  }

  const handleCopyKey = async (key: string) => {
    try {
      await navigator.clipboard.writeText(key)
      success('已复制到剪贴板')
    } catch {
      error('复制失败')
    }
  }

  const handleEditRealApiKey = (userKey: UserKey) => {
    setEditingKeyId(userKey.id)
    setEditingValue(userKey.real_api_key || '')
    setTimeout(() => editInputRef.current?.focus(), 0)
  }

  const handleSaveRealApiKey = async (userKey: UserKey) => {
    if (!id) return
    try {
      await request.put(`/packages/${id}/userkeys/${userKey.id}/real-api-key`, {
        real_api_key: editingValue
      })
      success('更新成功')
      setEditingKeyId(null)
      loadUserKeys()
    } catch (err) {
      console.error('failed to save real api key', err)
      error('更新失败')
    }
  }

  const handleViewUsageHistory = (apiKey: string) => {
    navigate(`/admin/user-key-usage/${apiKey}`)
  }

  const formatDate = (dateStr?: string) => {
    if (!dateStr) return '-'
    return new Date(dateStr).toLocaleString('zh-CN')
  }

  const getStatusType = (status: string) => {
    switch (status) {
      case 'active':
        return 'bg-green-100 text-green-800'
      case 'inactive':
        return 'bg-yellow-100 text-yellow-800'
      case 'expired':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const getStatusText = (status: string) => {
    switch (status) {
      case 'active':
        return '激活'
      case 'inactive':
        return '非激活'
      case 'expired':
        return '过期'
      default:
        return '未知'
    }
  }

  const getRemainingDaysClass = (days: number) => {
    if (days <= 0) return 'text-red-600 font-semibold'
    if (days <= 7) return 'text-orange-600 font-semibold'
    if (days <= 30) return 'text-yellow-600 font-semibold'
    return 'text-gray-600'
  }

  if (!id) return <div className="p-6">无效订阅ID</div>

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      {/* 顶部导航 */}
      <div className="mb-6 flex items-center gap-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={() => navigate('/admin/dashboard')}
          className="flex items-center gap-2"
        >
          <ArrowLeft size={18} />
          返回管理
        </Button>
        <h1 className="text-2xl font-bold text-gray-900">订阅详情</h1>
      </div>

      {/* 订阅基本信息 */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            📦 订阅信息
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loadingDetail ? (
            <div className="text-center py-8 text-gray-500">加载中...</div>
          ) : subscription ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div>
                <label className="text-sm text-gray-600">订阅名称</label>
                <div className="text-lg font-semibold text-gray-900">{subscription.package_name}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">订阅代码</label>
                <div className="text-lg font-semibold text-gray-900">{subscription.package_code}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">状态</label>
                <div className="mt-1">
                  <span className={`px-3 py-1 rounded-full text-sm font-medium ${
                    subscription.is_active ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                  }`}>
                    {subscription.is_active ? '可用' : '不可用'}
                  </span>
                </div>
              </div>
              <div>
                <label className="text-sm text-gray-600">价格</label>
                <div className="text-lg font-semibold text-gray-900">¥{subscription.price}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">积分</label>
                <div className="text-lg font-semibold text-gray-900">{subscription.credits}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">时长</label>
                <div className="text-lg font-semibold text-gray-900">{subscription.duration_days} 天</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">服务端点</label>
                <div className="text-sm text-gray-700">{subscription.endpoint || '未设置'}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">排序</label>
                <div className="text-lg font-semibold text-gray-900">{subscription.sort_order}</div>
              </div>
              <div>
                <label className="text-sm text-gray-600">创建时间</label>
                <div className="text-sm text-gray-700">{formatDate(subscription.created_at)}</div>
              </div>
              <div className="lg:col-span-4">
                <label className="text-sm text-gray-600">描述</label>
                <div className="text-sm text-gray-700 mt-1">{subscription.description || '暂无描述'}</div>
              </div>
            </div>
          ) : (
            <div className="text-center py-8 text-gray-500">未找到订阅</div>
          )}
        </CardContent>
      </Card>

      {/* 用户密钥管理 */}
      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0">
          <CardTitle className="flex items-center gap-2">
            🔑 用户密钥管理
          </CardTitle>
          <div className="flex gap-2">
            <Button
              size="sm"
              onClick={handleBatchGenerate}
              disabled={loadingBatchGenerate}
            >
              <Plus size={18} />
              批量生成 (10个)
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={() => setBulkOperationDialog(true)}
              disabled={selectedKeys.length === 0}
            >
              <Settings size={18} />
              批量操作 ({selectedKeys.length})
            </Button>
            <Button
              size="sm"
              variant="ghost"
              onClick={loadUserKeys}
            >
              <RotateCw size={18} />
              刷新
            </Button>
          </div>
        </CardHeader>

        <CardContent>
          {/* 筛选器 */}
          <div className="mb-4 pb-4 border-b border-gray-200">
            <select
              value={statusFilter}
              onChange={(e) => {
                setStatusFilter(e.target.value)
                setPagination(prev => ({ ...prev, page: 1 }))
              }}
              className="px-3 py-2 border border-gray-300 rounded-md text-sm"
            >
              <option value="">全部状态</option>
              <option value="active">激活</option>
              <option value="inactive">非激活</option>
              <option value="expired">过期</option>
            </select>
          </div>

          {/* 加载状态 */}
          {loadingUserKeys && (
            <div className="text-center py-8 text-gray-500">加载中...</div>
          )}

          {/* 用户密钥表格 */}
          {!loadingUserKeys && (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-8">
                    <input
                      type="checkbox"
                      onChange={(e) => {
                        if (e.target.checked) {
                          setSelectedKeys(userKeys)
                        } else {
                          setSelectedKeys([])
                        }
                      }}
                      checked={selectedKeys.length === userKeys.length && userKeys.length > 0}
                    />
                  </TableHead>
                  <TableHead>用户邮箱</TableHead>
                  <TableHead>用户Key</TableHead>
                  <TableHead>有效API Key</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>激活时间</TableHead>
                  <TableHead>过期时间</TableHead>
                  <TableHead>剩余天数</TableHead>
                  <TableHead>剩余积分</TableHead>
                  <TableHead>最后使用</TableHead>
                  <TableHead>操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {userKeys.map((userKey) => (
                  <TableRow key={userKey.id}>
                    <TableCell>
                      <input
                        type="checkbox"
                        checked={selectedKeys.some(k => k.id === userKey.id)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setSelectedKeys([...selectedKeys, userKey])
                          } else {
                            setSelectedKeys(selectedKeys.filter(k => k.id !== userKey.id))
                          }
                        }}
                      />
                    </TableCell>
                    <TableCell className="font-medium">{userKey.user_email}</TableCell>
                    <TableCell>
                      <div className="flex items-center gap-2">
                        <code className="text-xs bg-gray-100 px-2 py-1 rounded">
                          {userKey.api_key.substring(0, 10)}...
                        </code>
                        <button
                          onClick={() => handleCopyKey(userKey.api_key)}
                          className="p-1 hover:bg-gray-100 rounded"
                          title="复制"
                        >
                          <Copy size={16} className="text-gray-600" />
                        </button>
                      </div>
                    </TableCell>
                    <TableCell>
                      {editingKeyId === userKey.id ? (
                        <div className="flex gap-1">
                          <Input
                            ref={editInputRef}
                            size={undefined}
                            value={editingValue}
                            onChange={(e) => setEditingValue(e.target.value)}
                            className="text-xs"
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') {
                                handleSaveRealApiKey(userKey)
                              } else if (e.key === 'Escape') {
                                setEditingKeyId(null)
                              }
                            }}
                          />
                          <Button
                            size="sm"
                            onClick={() => handleSaveRealApiKey(userKey)}
                          >
                            保存
                          </Button>
                        </div>
                      ) : (
                        <div className="flex items-center gap-2 group">
                          <span className="text-xs text-gray-600">
                            {userKey.real_api_key || '未设置'}
                          </span>
                          <button
                            onClick={() => handleEditRealApiKey(userKey)}
                            className="p-1 hover:bg-gray-100 rounded opacity-0 group-hover:opacity-100"
                            title="编辑"
                          >
                            <Edit2 size={14} className="text-gray-600" />
                          </button>
                        </div>
                      )}
                    </TableCell>
                    <TableCell>
                      <span className={`px-2 py-1 rounded text-xs font-medium ${getStatusType(userKey.status)}`}>
                        {getStatusText(userKey.status)}
                      </span>
                    </TableCell>
                    <TableCell className="text-sm">{formatDate(userKey.activation_date)}</TableCell>
                    <TableCell className="text-sm">{formatDate(userKey.expire_date)}</TableCell>
                    <TableCell>
                      <span className={getRemainingDaysClass(userKey.remaining_days)}>
                        {userKey.activation_date ? `${userKey.remaining_days}天` : `${userKey.remaining_days}天(初始)`}
                      </span>
                    </TableCell>
                    <TableCell className="text-sm">
                      {userKey.remaining_credits} / {userKey.total_credits}
                    </TableCell>
                    <TableCell className="text-sm">{formatDate(userKey.last_used_at)}</TableCell>
                    <TableCell>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleViewUsageHistory(userKey.api_key)}
                        disabled={!userKey.api_key}
                      >
                        <Eye size={16} />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}

          {/* 分页 */}
          <div className="mt-4 flex items-center justify-between text-sm">
            <span className="text-gray-600">共 {pagination.total} 条</span>
            <div className="flex gap-2 items-center">
              <select
                value={pagination.size}
                onChange={(e) => {
                  setPagination(prev => ({ ...prev, size: parseInt(e.target.value), page: 1 }))
                }}
                className="px-2 py-1 border border-gray-300 rounded"
              >
                <option value="25">25条/页</option>
                <option value="50">50条/页</option>
                <option value="100">100条/页</option>
              </select>
              <Button
                size="sm"
                variant="outline"
                onClick={() => setPagination(prev => ({ ...prev, page: Math.max(1, prev.page - 1) }))}
                disabled={pagination.page === 1}
              >
                上一页
              </Button>
              <span className="px-2">{pagination.page}</span>
              <Button
                size="sm"
                variant="outline"
                onClick={() => setPagination(prev => ({ ...prev, page: prev.page + 1 }))}
                disabled={userKeys.length < pagination.size}
              >
                下一页
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* 批量操作对话框 */}
      <Dialog open={bulkOperationDialog} onOpenChange={setBulkOperationDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>批量操作</DialogTitle>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label htmlFor="operation">操作类型</Label>
              <select
                id="operation"
                value={bulkOperation.operation}
                onChange={(e) => setBulkOperation(prev => ({ ...prev, operation: e.target.value }))}
                className="w-full mt-1 px-3 py-2 border border-gray-300 rounded-md"
              >
                <option value="">选择操作类型</option>
                <option value="generate">生成密钥</option>
                <option value="activate">激活密钥</option>
                <option value="deactivate">禁用密钥</option>
                <option value="delete">删除密钥</option>
              </select>
            </div>

            <div>
              <Label htmlFor="notes">操作备注</Label>
              <textarea
                id="notes"
                value={bulkOperation.notes}
                onChange={(e) => setBulkOperation(prev => ({ ...prev, notes: e.target.value }))}
                className="w-full mt-1 px-3 py-2 border border-gray-300 rounded-md"
                rows={3}
                placeholder="可选的操作备注"
              />
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded p-3 text-sm text-blue-800">
              将对 <strong>{selectedKeys.length}</strong> 个用户密钥执行
              <strong className="ml-1">
                {bulkOperation.operation === 'generate' && '生成密钥'}
                {bulkOperation.operation === 'activate' && '激活密钥'}
                {bulkOperation.operation === 'deactivate' && '禁用密钥'}
                {bulkOperation.operation === 'delete' && '删除密钥'}
              </strong>
              操作
            </div>
          </div>

          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setBulkOperationDialog(false)}
            >
              取消
            </Button>
            <Button
              onClick={handleBulkOperation}
              disabled={!bulkOperation.operation || loadingBulkOperation}
            >
              确认执行
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

export default SubscriptionDetail

// frontend/src/views/admin/SubscriptionDetail.vue
<template>
  <div class="subscription-detail-page">
    <div class="container-fluid">
      <!-- 面包屑导航 -->
      <div class="breadcrumb-section">
        <ElBreadcrumb separator="/">
          <ElBreadcrumbItem @click="goBack" class="clickable">订阅管理</ElBreadcrumbItem>
          <ElBreadcrumbItem>订阅详情</ElBreadcrumbItem>
        </ElBreadcrumb>
      </div>

      <!-- 订阅基本信息 -->
      <div class="subscription-info-section">
        <ElCard shadow="never" class="info-card">
          <template #header>
            <div class="card-header">
              <h3>
                <i class="fas fa-cube"></i>
                订阅信息
              </h3>
            </div>
          </template>

          <div v-if="loading.detail" class="loading-container">
            <ElSkeleton :rows="3" animated />
          </div>

          <div v-else-if="subscription" class="subscription-info">
            <ElDescriptions :column="3" border>
              <ElDescriptionsItem label="订阅名称">
                {{ subscription.package_name }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="订阅代码">
                {{ subscription.package_code }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="状态">
                <ElTag :type="subscription.is_active ? 'success' : 'danger'">
                  {{ subscription.is_active ? '可用' : '不可用' }}
                </ElTag>
              </ElDescriptionsItem>
              <ElDescriptionsItem label="服务端点">
                {{ subscription.endpoint || '未设置' }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="价格">
                ¥{{ subscription.price }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="积分">
                {{ subscription.credits }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="时长">
                {{ subscription.duration_days }} 天
              </ElDescriptionsItem>
              <ElDescriptionsItem label="排序">
                {{ subscription.sort_order }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="创建时间">
                {{ formatDate(subscription.created_at) }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="描述" :span="3">
                {{ subscription.description || '暂无描述' }}
              </ElDescriptionsItem>
            </ElDescriptions>
          </div>
        </ElCard>
      </div>

      <!-- 用户密钥管理 -->
      <div class="userkeys-section">
        <ElCard shadow="never" class="userkeys-card">
          <template #header>
            <div class="card-header">
              <h3>
                <i class="fas fa-key"></i>
                用户密钥管理
              </h3>
              <div class="header-actions">
                <ElButton
                  type="success"
                  @click="batchGenerateUserKeys"
                  :loading="loading.batchGenerate"
                >
                  <i class="fas fa-plus-circle"></i>
                  批量生成 (10个)
                </ElButton>
                <ElButton
                  type="primary"
                  @click="showBulkOperationDialog"
                  :disabled="selectedUserKeys.length === 0"
                >
                  <i class="fas fa-cogs"></i>
                  批量操作 ({{ selectedUserKeys.length }})
                </ElButton>
                <ElButton @click="refreshUserKeys" :loading="loading.userKeys">
                  <i class="fas fa-sync-alt"></i>
                  刷新
                </ElButton>
              </div>
            </div>
          </template>

          <!-- 筛选器 -->
          <div class="filter-section">
            <ElRow :gutter="20">
              <ElCol :span="6">
                <ElSelect
                  v-model="userKeyFilter.status"
                  placeholder="状态筛选"
                  clearable
                  @change="loadUserKeys"
                >
                  <ElOption label="全部" value="" />
                  <ElOption label="激活" value="active" />
                  <ElOption label="非激活" value="inactive" />
                  <ElOption label="过期" value="expired" />
                </ElSelect>
              </ElCol>
            </ElRow>
          </div>

          <!-- 用户密钥列表 -->
          <div class="userkeys-table">
            <ElTable
              v-loading="loading.userKeys"
              :data="userKeys"
              @selection-change="handleSelectionChange"
              style="width: 100%"
            >
              <ElTableColumn type="selection" width="55" />
              <ElTableColumn prop="user_email" label="用户邮箱" width="200" />
              <ElTableColumn prop="api_key" label="用户Key" width="250">
                <template #default="scope">
                  <div class="user-key-container">
                    <code class="api-key">{{ truncateKey(scope.row.api_key) }}</code>
                    <ElButton
                      type="primary"
                      size="small"
                      @click="copyToClipboard(scope.row.api_key)"
                      class="copy-btn"
                    >
                      <i class="fas fa-copy"></i>
                    </ElButton>
                  </div>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="real_api_key" label="有效API Key" width="300">
                <template #default="scope">
                  <div class="real-api-key-container">
                    <ElInput
                      v-if="editingRealApiKey[scope.row.id]"
                      v-model="editRealApiKeyValue"
                      size="small"
                      placeholder="输入有效API Key"
                      @blur="saveRealApiKey(scope.row)"
                      @keyup.enter="saveRealApiKey(scope.row)"
                      @keyup.esc="cancelEditRealApiKey(scope.row.id)"
                      style="flex: 1;"
                    />
                    <span
                      v-else
                      class="real-api-key-text"
                      @dblclick="startEditRealApiKey(scope.row)"
                      :title="scope.row.real_api_key || '双击编辑'"
                    >
                      {{ scope.row.real_api_key || '未设置' }}
                    </span>
                    <ElButton
                      v-if="!editingRealApiKey[scope.row.id]"
                      type="text"
                      size="small"
                      @click="startEditRealApiKey(scope.row)"
                      class="edit-btn"
                    >
                      <i class="fas fa-edit"></i>
                    </ElButton>
                  </div>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="status" label="状态" width="100">
                <template #default="scope">
                  <ElTag :type="getStatusType(scope.row.status)">
                    {{ getStatusText(scope.row.status) }}
                  </ElTag>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="activation_date" label="激活时间" width="180">
                <template #default="scope">
                  {{ scope.row.activation_date ? formatDate(scope.row.activation_date) : '未激活' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="expire_date" label="过期时间" width="180">
                <template #default="scope">
                  {{ scope.row.expire_date ? formatDate(scope.row.expire_date) : '-' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="remaining_days" label="剩余天数" width="120">
                <template #default="scope">
                  <span v-if="scope.row.activation_date" :class="getRemainingDaysClass(scope.row.remaining_days)">
                    {{ scope.row.remaining_days }} 天
                  </span>
                  <span v-else class="inactive">
                    {{ scope.row.remaining_days }} 天 (初始)
                  </span>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="remaining_credits" label="剩余积分" width="120">
                <template #default="scope">
                  <span class="credits">
                    {{ scope.row.remaining_credits || 0 }} / {{ scope.row.total_credits || 0 }}
                  </span>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="last_used_at" label="最后使用" width="180">
                <template #default="scope">
                  {{ formatDate(scope.row.last_used_at) || '未使用' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="notes" label="备注" min-width="150" />
              <ElTableColumn label="操作" width="120" fixed="right">
                <template #default="scope">
                  <ElButton
                    type="primary"
                    size="small"
                    @click="viewUsageHistory(scope.row)"
                    :disabled="!scope.row.api_key"
                  >
                    <i class="fas fa-chart-line"></i>
                    使用履历
                  </ElButton>
                </template>
              </ElTableColumn>
            </ElTable>
          </div>

          <!-- 分页 -->
          <div class="pagination-container">
            <ElPagination
              v-model:current-page="pagination.page"
              v-model:page-size="pagination.size"
              :page-sizes="[25, 50, 100]"
              :total="pagination.total"
              layout="total, sizes, prev, pager, next, jumper"
              @size-change="handleSizeChange"
              @current-change="handlePageChange"
            />
          </div>
        </ElCard>
      </div>
    </div>

    <!-- 批量操作对话框 -->
    <ElDialog
      v-model="bulkOperationVisible"
      title="批量操作"
      width="500px"
      :before-close="handleCloseBulkOperation"
    >
      <ElForm :model="bulkOperation" label-width="100px">
        <ElFormItem label="操作类型">
          <ElSelect v-model="bulkOperation.operation" placeholder="选择操作类型">
            <ElOption label="生成密钥" value="generate" />
            <ElOption label="激活密钥" value="activate" />
            <ElOption label="禁用密钥" value="deactivate" />
            <ElOption label="删除密钥" value="delete" />
          </ElSelect>
        </ElFormItem>
        <ElFormItem label="操作备注">
          <ElInput
            v-model="bulkOperation.notes"
            type="textarea"
            :rows="3"
            placeholder="可选的操作备注"
          />
        </ElFormItem>
        <ElFormItem>
          <div class="operation-info">
            <p>将对 <strong>{{ selectedUserKeys.length }}</strong> 个用户密钥执行 <strong>{{ getOperationText(bulkOperation.operation) }}</strong> 操作</p>
          </div>
        </ElFormItem>
      </ElForm>
      <template #footer>
        <span class="dialog-footer">
          <ElButton @click="bulkOperationVisible = false">取消</ElButton>
          <ElButton
            type="primary"
            @click="executeBulkOperation"
            :loading="loading.bulkOperation"
            :disabled="!bulkOperation.operation"
          >
            确认执行
          </ElButton>
        </span>
      </template>
    </ElDialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, nextTick } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  ElCard, ElButton, ElBreadcrumb, ElBreadcrumbItem, ElDescriptions, ElDescriptionsItem,
  ElTag, ElSkeleton, ElTable, ElTableColumn, ElSelect, ElOption, ElRow, ElCol,
  ElPagination, ElDialog, ElForm, ElFormItem, ElInput
} from 'element-plus'
import request from '../../utils/request'

interface Subscription {
  id: number
  package_code: string
  package_name: string
  description?: string
  endpoint?: string
  price: number
  credits: number
  duration_days: number
  is_active: boolean
  sort_order: number
  created_at: string
  updated_at: string
}

interface UserKey {
  id: number
  user_id: string
  api_key_id: number
  api_key: string
  real_api_key?: string  // 添加real_api_key字段
  key_name?: string
  description?: string
  user_email: string
  activation_date?: string | null
  status: string
  notes?: string
  last_used_at?: string | null
  expire_date?: string | null
  remaining_days: number
  remaining_credits: number
  total_credits: number
  created_at: string
}

const route = useRoute()
const router = useRouter()

const subscription = ref<Subscription | null>(null)
const userKeys = ref<UserKey[]>([])
const selectedUserKeys = ref<UserKey[]>([])
const bulkOperationVisible = ref(false)

// 编辑real_api_key相关状态
const editingRealApiKey = ref<Record<number, boolean>>({})
const editRealApiKeyValue = ref('')

const loading = reactive({
  detail: false,
  userKeys: false,
  bulkOperation: false,
  batchGenerate: false
})

const userKeyFilter = reactive({
  status: ''
})

const pagination = reactive({
  page: 1,
  size: 50,
  total: 0
})

const bulkOperation = reactive({
  operation: '',
  notes: ''
})

// 获取订阅详情
const loadSubscriptionDetail = async () => {
  try {
    loading.detail = true
    const packageId = route.params.id
    const response: any = await request.get(`/api/v1/packages/${packageId}`)
    subscription.value = response
  } catch (error) {
    console.error('加载订阅详情失败:', error)
    ElMessage.error('加载订阅详情失败')
  } finally {
    loading.detail = false
  }
}

// 获取用户密钥列表
const loadUserKeys = async () => {
  try {
    loading.userKeys = true
    const packageId = route.params.id
    const params = {
      page: pagination.page,
      page_size: pagination.size,
      status_filter: userKeyFilter.status || undefined
    }

    const response: any = await request.get(`/api/v1/packages/${packageId}/userkeys`, { params })

    userKeys.value = response.user_keys || []
    pagination.total = response.total || 0
  } catch (error) {
    console.error('加载用户密钥列表失败:', error)
    ElMessage.error('加载用户密钥列表失败')
  } finally {
    loading.userKeys = false
  }
}

// 刷新用户密钥列表
const refreshUserKeys = () => {
  loadUserKeys()
}

// 分页处理
const handlePageChange = (page: number) => {
  pagination.page = page
  loadUserKeys()
}

const handleSizeChange = (size: number) => {
  pagination.size = size
  pagination.page = 1
  loadUserKeys()
}

// 选择处理
const handleSelectionChange = (selection: UserKey[]) => {
  selectedUserKeys.value = selection
}

// 批量操作
const showBulkOperationDialog = () => {
  bulkOperationVisible.value = true
}

const handleCloseBulkOperation = () => {
  bulkOperationVisible.value = false
  bulkOperation.operation = ''
  bulkOperation.notes = ''
}

const executeBulkOperation = async () => {
  try {
    loading.bulkOperation = true
    const packageId = route.params.id

    const operationData = {
      user_ids: selectedUserKeys.value.map(uk => uk.user_id),
      api_key_id: selectedUserKeys.value[0]?.api_key_id,
      operation: bulkOperation.operation,
      notes: bulkOperation.notes
    }

    const response: any = await request.post(`/api/v1/packages/${packageId}/userkeys/batch`, operationData)
    ElMessage.success(response.message || '批量操作成功')

    // 重新加载用户密钥列表
    await loadUserKeys()

    // 关闭对话框
    handleCloseBulkOperation()
    selectedUserKeys.value = []

  } catch (error) {
    console.error('批量操作失败:', error)
    ElMessage.error('批量操作失败')
  } finally {
    loading.bulkOperation = false
  }
}

// 工具函数
const goBack = () => {
  router.push('/admin/dashboard')
}

const formatDate = (dateString: string) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('zh-CN')
}

const getStatusType = (status: string) => {
  switch (status) {
    case 'active': return 'success'
    case 'inactive': return 'warning'
    case 'expired': return 'danger'
    default: return 'info'
  }
}

const getStatusText = (status: string) => {
  switch (status) {
    case 'active': return '激活'
    case 'inactive': return '非激活'
    case 'expired': return '过期'
    default: return '未知'
  }
}

const getRemainingDaysClass = (days: number) => {
  if (days <= 0) return 'expired'
  if (days <= 7) return 'warning'
  if (days <= 30) return 'attention'
  return 'normal'
}

const getOperationText = (operation: string) => {
  switch (operation) {
    case 'generate': return '生成密钥'
    case 'activate': return '激活密钥'
    case 'deactivate': return '禁用密钥'
    case 'delete': return '删除密钥'
    default: return operation
  }
}

// 批量生成user key
const batchGenerateUserKeys = async () => {
  try {
    loading.batchGenerate = true
    const packageId = route.params.id

    const response: any = await request.post(`/api/v1/packages/${packageId}/userkeys/batch-generate`, {
      count: 10,
      status: 'inactive'
    })

    ElMessage.success(response.message || '批量生成用户密钥成功')

    // 刷新用户密钥列表
    await loadUserKeys()

  } catch (error) {
    console.error('批量生成用户密钥失败:', error)
    ElMessage.error('批量生成用户密钥失败')
  } finally {
    loading.batchGenerate = false
  }
}

// 截断显示用户Key
const truncateKey = (key: string) => {
  if (!key) return ''
  return key.length > 10 ? `${key.substring(0, 10)}...` : key
}

// 编辑real_api_key相关方法
const startEditRealApiKey = (userKey: UserKey) => {
  editingRealApiKey.value[userKey.id] = true
  editRealApiKeyValue.value = userKey.real_api_key || ''
  // 等待下一个tick，确保输入框渲染完成后聚焦
  nextTick(() => {
    const container = document.querySelector('.real-api-key-container')
    const input = container?.querySelector('input') as HTMLInputElement
    if (input) {
      input.focus()
      input.select()
    }
  })
}

const cancelEditRealApiKey = (userKeyId: number) => {
  editingRealApiKey.value[userKeyId] = false
  editRealApiKeyValue.value = ''
}

const saveRealApiKey = async (userKey: UserKey) => {
  try {
    const packageId = route.params.id

    await request.put(`/api/v1/packages/${packageId}/userkeys/${userKey.id}/real-api-key`, {
      real_api_key: editRealApiKeyValue.value
    })

    // 更新本地数据
    userKey.real_api_key = editRealApiKeyValue.value

    // 退出编辑模式
    editingRealApiKey.value[userKey.id] = false
    editRealApiKeyValue.value = ''

    ElMessage.success('更新成功')
  } catch (error) {
    console.error('更新real_api_key失败:', error)
    ElMessage.error('更新失败')
  }
}

// 拷贝到剪贴板
const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success('用户Key已复制到剪贴板')
  } catch (error) {
    // 兼容不支持clipboard API的浏览器
    const textArea = document.createElement('textarea')
    textArea.value = text
    document.body.appendChild(textArea)
    textArea.select()
    document.execCommand('copy')
    document.body.removeChild(textArea)
    ElMessage.success('用户Key已复制到剪贴板')
  }
}

// 查看使用履历
const viewUsageHistory = (userKey: UserKey) => {
  router.push(`/admin/user-key-usage/${userKey.api_key}`)
}

onMounted(() => {
  loadSubscriptionDetail()
  loadUserKeys()
})
</script>

<style scoped>
.subscription-detail-page {
  padding: 20px;
  background-color: #f5f7fa;
  min-height: 100vh;
}

.breadcrumb-section {
  margin-bottom: 20px;
}

.breadcrumb-section .clickable {
  cursor: pointer;
  color: #409eff;
}

.breadcrumb-section .clickable:hover {
  text-decoration: underline;
}

.subscription-info-section {
  margin-bottom: 24px;
}

.userkeys-section {
  margin-bottom: 24px;
}

.info-card, .userkeys-card {
  border: none;
  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-header h3 {
  margin: 0;
  font-size: 1.2rem;
  font-weight: 600;
  color: #2c3e50;
  display: flex;
  align-items: center;
  gap: 8px;
}

.header-actions {
  display: flex;
  gap: 12px;
}

.loading-container {
  padding: 20px;
}

.subscription-info {
  padding: 20px 0;
}

.filter-section {
  margin-bottom: 20px;
  padding: 16px 0;
  border-bottom: 1px solid #f0f2f5;
}

.userkeys-table {
  margin-bottom: 20px;
}

.user-key-container {
  display: flex;
  align-items: center;
  gap: 8px;
}

.api-key {
  background: #f5f7fa;
  padding: 2px 6px;
  border-radius: 4px;
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 12px;
  flex: 1;
  min-width: 0;
}

.copy-btn {
  flex-shrink: 0;
  padding: 4px 8px;
}

.real-api-key-container {
  display: flex;
  align-items: center;
  gap: 8px;
}

.real-api-key-text {
  flex: 1;
  cursor: pointer;
  padding: 2px 4px;
  border-radius: 4px;
  min-height: 20px;
  display: flex;
  align-items: center;
  color: #606266;
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 12px;
}

.real-api-key-text:hover {
  background-color: #f5f7fa;
}

.edit-btn {
  flex-shrink: 0;
  padding: 4px 8px;
}

.credits {
  font-weight: 600;
}

.expired {
  color: #f56c6c;
  font-weight: 600;
}

.warning {
  color: #e6a23c;
  font-weight: 600;
}

.attention {
  color: #409eff;
}

.normal {
  color: #67c23a;
}

.inactive {
  color: #909399;
  font-style: italic;
}

.pagination-container {
  display: flex;
  justify-content: center;
  padding: 20px;
  border-top: 1px solid #f0f2f5;
}

.operation-info {
  background: #ecf5ff;
  padding: 12px;
  border-radius: 4px;
  border-left: 4px solid #409eff;
}

.operation-info p {
  margin: 0;
  color: #606266;
}

/* 移动端适配 */
@media (max-width: 768px) {
  .subscription-detail-page {
    padding: 16px;
  }

  .card-header {
    flex-direction: column;
    gap: 12px;
  }

  .header-actions {
    width: 100%;
    justify-content: flex-end;
  }
}

/* 深色主题支持 */
:global(.dark-theme) .subscription-detail-page {
  background-color: #0d1117;
}

:global(.dark-theme) .card-header h3 {
  color: #f0f6fc;
}

:global(.dark-theme) .api-key {
  background: #21262d;
  color: #f0f6fc;
}
</style>
