// frontend-react/src/pages/Login.tsx
import React, { useEffect } from 'react'
import { useNavigate, useLocation, Link } from 'react-router-dom'
import { useForm } from 'react-hook-form'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Alert, AlertDescription } from '@/components/ui/alert'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { useUserStore } from '@/store/user'
import request from '@/utils/request'

interface LoginForm {
  email: string
  password: string
}

interface LoginResponse {
  user: {
    user_id: string
    email: string
    phone?: string
    is_active: boolean
    is_email_verified: boolean
    last_login_at?: string
    created_at: string
  }
  tokens: {
    access_token: string
    refresh_token: string
    token_type: string
    expires_in: number
  }
}

const Login: React.FC = () => {
  const navigate = useNavigate()
  const location = useLocation()
  const { login } = useUserStore()

  // 使用react-hook-form管理表单状态
  const form = useForm<LoginForm>({
    defaultValues: {
      email: '',
      password: '',
    },
  })

  const [loading, setLoading] = React.useState(false)
  const [serverError, setServerError] = React.useState('')

  // 从URL参数获取邮箱（验证成功后传递）
  useEffect(() => {
    const searchParams = new URLSearchParams(location.search)
    const email = searchParams.get('email')
    const verified = searchParams.get('verified')

    if (email) {
      form.setValue('email', email)
      if (verified === 'true') {
        // 可以在这里添加成功消息显示
        console.log('邮箱验证成功！请输入密码登录')
      }
    }
  }, [location.search, form])

  // 表单提交处理
  const onSubmit = async (data: LoginForm) => {
    console.log('开始登录流程...')

    setLoading(true)
    setServerError('')

    try {
      const response: LoginResponse = await request.post('/auth/login', {
        email: data.email,
        password: data.password
      })

      // 保存用户信息和token
      console.log('登录成功，保存用户信息到状态管理')
      login({
        id: response.user.user_id,
        name: response.user.email,
        email: response.user.email,
        token: response.tokens.access_token,
        refreshToken: response.tokens.refresh_token
      })

      // 立即跳转到仪表板
      console.log('用户登录成功，立即跳转到仪表板')
      navigate('/app/dashboard', { replace: true })

    } catch (error: any) {
      console.error('登录失败:', error)

      // 服务器端登录错误处理
      if (error.response?.status === 401) {
        setServerError('邮箱或密码错误，请重新输入')
      } else if (error.response?.data?.detail) {
        setServerError(error.response.data.detail)
      } else {
        setServerError('登录失败，请稍后重试')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-muted flex">
      {/* 左侧品牌展示区 (桌面端70%) */}
      <div className="hidden lg:flex lg:flex-1 lg:flex-col lg:justify-center lg:items-center bg-card text-card-foreground p-12">
        <div className="max-w-md text-center">
          <div className="mb-8">
            <div className="w-24 h-24 bg-muted rounded-full flex items-center justify-center mx-auto mb-6 border-2 border-primary">
              <svg className="w-12 h-12 text-primary" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M10 1a4.5 4.5 0 00-4.5 4.5V9H5a2 2 0 00-2 2v6a2 2 0 002 2h10a2 2 0 002-2v-6a2 2 0 00-2-2h-.5V5.5A4.5 4.5 0 0010 1zm3 8V5.5a3 3 0 10-6 0V9h6z" clipRule="evenodd" />
              </svg>
            </div>
            <h1 className="text-4xl font-bold">agnets.app</h1>
          </div>

          <div>
            <h2 className="text-2xl font-semibold mb-4">欢迎回来</h2>
            <p className="text-muted-foreground text-lg">安全、高效的AI工具</p>
          </div>
        </div>
      </div>

      {/* 右侧登录表单区 (桌面端30%) */}
      <div className="flex-1 flex flex-col justify-center items-center p-8 bg-background">
        <div className="w-full max-w-sm">
          <Card className="border-0 shadow-none lg:shadow-lg">
            <CardHeader className="text-center pb-6">
              <CardTitle className="text-2xl font-bold">欢迎回来</CardTitle>
              <CardDescription className="text-base">
                登录到您的agnets.app账户
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                  {/* 邮箱字段 */}
                  <FormField
                    control={form.control}
                    name="email"
                    rules={{
                      required: '请输入邮箱地址',
                      pattern: {
                        value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                        message: '请输入有效的邮箱地址'
                      }
                    }}
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>邮箱地址</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            type="email"
                            placeholder="邮箱地址"
                            className="h-12 text-base"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* 密码字段 */}
                  <FormField
                    control={form.control}
                    name="password"
                    rules={{
                      required: '请输入密码',
                      minLength: {
                        value: 6,
                        message: '密码长度不能少于6位'
                      }
                    }}
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>密码</FormLabel>
                        <FormControl>
                          <Input
                            {...field}
                            type="password"
                            placeholder="密码"
                            className="h-12 text-base"
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  {/* 服务器错误提示 */}
                  {serverError && (
                    <Alert variant="destructive">
                      <AlertDescription>
                        {serverError}
                      </AlertDescription>
                    </Alert>
                  )}

                  <Button
                    type="submit"
                    className="w-full h-12 text-base font-semibold"
                    disabled={loading}
                  >
                    {loading ? '登录中...' : '登录'}
                  </Button>
                </form>
              </Form>

              <div className="mt-6 text-center space-y-3">
                <p className="text-sm text-muted-foreground">
                  还没有账户？
                  <Link to="/register" className="text-primary hover:text-primary/80 font-medium ml-1">
                    立即注册
                  </Link>
                </p>
                <Link
                  to="/forgot-password"
                  className="text-sm text-muted-foreground hover:text-foreground block"
                >
                  忘记密码？
                </Link>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

export default Login

// frontend/src/views/auth/Login.vue
<template>
  <div class="login-page">
    <div class="login-container">
      <!-- 左侧品牌展示区 (桌面端70%) -->
      <div class="brand-section">
        <div class="brand-content">
          <div class="brand-logo">
            <div class="logo-icon">
              <i class="fas fa-key"></i>
            </div>
            <h1 class="brand-title">agnets.app</h1>
          </div>

          <div class="brand-slogan">
            <h2>欢迎回来</h2>
            <p class="lead">安全、高效的AI工具</p>
          </div>
        </div>
      </div>

      <!-- 右侧登录表单区 (桌面端30%) -->
      <div class="auth-section">
        <div class="auth-card">
          <div class="auth-header">
            <h2 class="auth-title">欢迎回来</h2>
            <p class="auth-subtitle">登录到您的agnets.app账户</p>
          </div>

          <ElForm
            :model="loginForm"
            :rules="loginRules"
            ref="loginFormRef"
            @submit.prevent="handleLogin"
            class="auth-form"
          >
            <ElFormItem prop="email">
              <ElInput
                v-model="loginForm.email"
                placeholder="邮箱地址"
                type="email"
                size="large"
                :prefix-icon="ElIconUser"
                @keyup.enter="handleLogin"
                @input="clearLoginError"
              />
            </ElFormItem>

            <ElFormItem prop="password">
              <ElInput
                v-model="loginForm.password"
                placeholder="密码"
                type="password"
                size="large"
                :prefix-icon="ElIconLock"
                show-password
                @keyup.enter="handleLogin"
                @input="clearLoginError"
              />
            </ElFormItem>

            <!-- 登录错误提示 -->
            <div v-if="loginError" class="login-error" key="login-error">
              <i class="fas fa-exclamation-circle"></i>
              {{ loginError }}
            </div>

            <ElFormItem>
              <ElButton
                type="primary"
                size="large"
                class="auth-submit-btn"
                :loading="loading"
                @click="handleLogin"
              >
                登录
              </ElButton>
            </ElFormItem>
          </ElForm>

          <div class="auth-footer">
            <p class="auth-link">
              还没有账户？
              <router-link to="/register" class="link-primary">立即注册</router-link>
            </p>
            <router-link to="/forgot-password" class="link-muted">
              忘记密码？
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElForm, ElFormItem, ElInput, ElButton, ElMessage } from 'element-plus'
import { User as ElIconUser, Lock as ElIconLock } from '@element-plus/icons-vue'
import { useUserStore } from '../../store/user'
import { useThemeStore } from '../../store/theme'
import request from '../../utils/request'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()
const themeStore = useThemeStore()

const loading = ref(false)
const loginFormRef = ref()
const loginError = ref('')

const loginForm = reactive({
  email: '',
  password: ''
})

const loginRules = {
  email: [
    { required: true, message: '请输入邮箱地址', trigger: 'blur' },
    { type: 'email' as const, message: '请输入正确的邮箱格式', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码长度不能少于6位', trigger: 'blur' }
  ]
}

// 定义登录响应的类型
interface LoginResponse {
  user: {
    user_id: string
    email: string
    phone?: string
    is_active: boolean
    is_email_verified: boolean
    last_login_at?: string
    created_at: string
  }
  tokens: {
    access_token: string
    refresh_token: string
    token_type: string
    expires_in: number
  }
}

const handleLogin = async () => {
  if (!loginFormRef.value) return

  // 清除之前的错误信息
  loginError.value = ''

  // 先进行客户端表单验证
  try {
    await loginFormRef.value.validate()
  } catch (validationError) {
    // 表单验证失败，显示客户端校验错误提示
    loginError.value = '请检查表单填写是否正确'
    return
  }

  // 表单验证通过，开始登录请求
  loading.value = true

  try {
    const response: LoginResponse = await request.post('/api/v1/auth/login', {
      email: loginForm.email,
      password: loginForm.password
    })

    // 保存用户信息和token
    userStore.login({
      id: response.user.user_id,
      name: response.user.email,
      email: response.user.email,
      token: response.tokens.access_token,
      refreshToken: response.tokens.refresh_token
    })

    ElMessage.success('登录成功')

    // 根据用户是否有激活密钥决定跳转页面
    try {
      const hasActiveKeys = await userStore.hasActiveApiKeys()
      const redirectPath = hasActiveKeys ? '/dashboard' : '/key-activation'
      console.log(`用户登录成功，${hasActiveKeys ? '有激活密钥' : '无激活密钥'}，跳转到: ${redirectPath}`)
      router.push(redirectPath)
    } catch (error) {
      console.error('检查用户密钥状态失败:', error)
      // 如果检查失败，默认跳转到控制台
      router.push('/dashboard')
    }

  } catch (error: any) {
    console.error('登录失败:', error)

    // 服务器端登录错误处理 - 显示在表单上
    if (error.response?.status === 401) {
      loginError.value = '邮箱或密码错误，请重新输入'
    } else if (error.response?.data?.detail) {
      loginError.value = error.response.data.detail
    } else {
      loginError.value = '登录失败，请稍后重试'
    }
  } finally {
    loading.value = false
  }
}

const clearLoginError = () => {
  if (loginError.value) {
    loginError.value = ''
  }
}

onMounted(() => {
  themeStore.initializeTheme()

  // 从URL参数获取邮箱（验证成功后传递）
  const email = route.query.email as string
  const verified = route.query.verified as string

  if (email) {
    loginForm.email = email

    if (verified === 'true') {
      ElMessage.success('邮箱验证成功！请输入密码登录')
    }
  }
})
</script>

<style scoped>
.login-page {
  height: 100vh;
  background: #f8f9fa;
  overflow: hidden;
}

.login-container {
  display: flex;
  height: 100vh;
}

/* 左侧品牌区域 (桌面端70%) */
.brand-section {
  flex: 0 0 70%;
  background: #2c3e50;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px;
  color: white;
  position: relative;
}

.brand-content {
  text-align: center;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  height: 100%;
}

.brand-logo {
  margin-bottom: 40px;
}

.logo-icon {
  width: 120px;
  height: 120px;
  background: #34495e;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 30px;
  border: 3px solid #3498db;
}

.logo-icon i {
  font-size: 48px;
  color: #3498db;
}

.brand-title {
  font-size: 3.5rem;
  font-weight: 700;
  margin: 0;
  letter-spacing: -1px;
  color: white;
}

.brand-slogan {
  margin-bottom: 0;
}

.brand-slogan h2 {
  font-size: 2rem;
  font-weight: 600;
  margin-bottom: 20px;
  color: #ecf0f1;
}

.brand-slogan .lead {
  font-size: 1.25rem;
  color: #bdc3c7;
  font-weight: 300;
}


/* 右侧登录区域 (桌面端30%) */
.auth-section {
  flex: 0 0 30%;
  background: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px 40px;
  box-shadow: -10px 0 30px rgba(0,0,0,0.1);
}

.auth-card {
  width: 100%;
  max-width: 400px;
  position: relative;
}

.auth-header {
  text-align: center;
  margin-bottom: 40px;
}

.auth-title {
  font-size: 2rem;
  font-weight: 700;
  color: #2c3e50;
  margin: 0 0 12px 0;
}

.auth-subtitle {
  font-size: 1rem;
  color: #7f8c8d;
  margin: 0;
}

.auth-form {
  margin-bottom: 30px;
}

.auth-form .el-form-item {
  margin-bottom: 24px;
}

/* 登录错误提示样式 */
.login-error {
  background: #fef0f0;
  border: 1px solid #fbc4c4;
  border-radius: 8px;
  padding: 12px 16px;
  margin-bottom: 20px;
  color: #f56565;
  font-size: 14px;
  display: flex;
  align-items: center;
  gap: 8px;
  position: relative;
  z-index: 10;
  transition: all 0.3s ease;
}

.login-error i {
  font-size: 16px;
}

.auth-submit-btn {
  width: 100%;
  height: 48px;
  font-size: 16px;
  font-weight: 600;
  border-radius: 8px;
  background: #3498db;
  border: none;
  box-shadow: 0 4px 15px rgba(52, 152, 219, 0.4);
  transition: all 0.3s ease;
}

.auth-submit-btn:hover {
  background: #2980b9;
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(52, 152, 219, 0.5);
}

.auth-footer {
  text-align: center;
}

.auth-link {
  margin: 0 0 15px 0;
  color: #7f8c8d;
  font-size: 14px;
}

.link-primary {
  color: #3498db;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.3s ease;
}

.link-primary:hover {
  color: #2980b9;
  text-decoration: underline;
}

.link-muted {
  color: #95a5a6;
  text-decoration: none;
  font-size: 13px;
  transition: color 0.3s ease;
}

.link-muted:hover {
  color: #3498db;
  text-decoration: underline;
}

/* 平板端适配 (768px - 1024px) */
@media (max-width: 1024px) {
  .brand-section {
    flex: 0 0 60%;
    padding: 40px;
  }

  .auth-section {
    flex: 0 0 40%;
    padding: 40px 30px;
  }

  .brand-title {
    font-size: 2.5rem;
  }

  .brand-slogan h2 {
    font-size: 1.5rem;
  }

  .feature-item {
    padding: 20px;
    margin-bottom: 30px;
  }
}

/* 移动端适配 (隐藏品牌区域) */
@media (max-width: 768px) {
  .login-container {
    flex-direction: column;
  }

  .brand-section {
    display: none;
  }

  .auth-section {
    flex: 1;
    min-height: 100vh;
    padding: 40px 20px;
    background: #f8f9fa;
    box-shadow: none;
  }

  .auth-card {
    background: #ffffff;
    border-radius: 20px;
    padding: 40px 30px;
    box-shadow: 0 20px 40px rgba(0,0,0,0.1);
    border: 1px solid #e1e8ed;
  }

  .auth-title {
    color: #2c3e50;
  }

  .auth-subtitle {
    color: #5a6c7d;
  }
}

/* 小屏移动端 */
@media (max-width: 480px) {
  .auth-section {
    padding: 20px 15px;
  }

  .auth-card {
    padding: 30px 20px;
  }

  .auth-title {
    font-size: 1.5rem;
  }
}

/* 确保Element Plus组件样式 */
:deep(.el-input__wrapper) {
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.05);
  border: 1px solid #e1e8ed;
  transition: all 0.3s ease;
}

:deep(.el-input__wrapper:hover) {
  border-color: #3498db;
  box-shadow: 0 2px 12px rgba(52, 152, 219, 0.15);
}

:deep(.el-input__wrapper.is-focus) {
  border-color: #3498db;
  box-shadow: 0 0 0 2px rgba(52, 152, 219, 0.2);
}

:deep(.el-input__inner) {
  height: 48px;
  font-size: 15px;
}

:deep(.el-form-item__error) {
  margin-top: 8px;
}

/* Dark Theme Styles */
:global(.dark-theme) .login-page {
  background: #1a1a1a;
}

:global(.dark-theme) .brand-section {
  background: #0f1419;
}

:global(.dark-theme) .brand-title {
  color: #ffffff;
}

:global(.dark-theme) .brand-slogan h2 {
  color: #e1e8ed;
}

:global(.dark-theme) .brand-slogan .lead {
  color: #8b949e;
}


:global(.dark-theme) .auth-section {
  background: #161b22;
  box-shadow: -10px 0 30px rgba(0,0,0,0.3);
}

:global(.dark-theme) .auth-card {
  background: #0d1117;
  border: 1px solid #30363d;
}

:global(.dark-theme) .auth-title {
  color: #f0f6fc;
}

:global(.dark-theme) .auth-subtitle {
  color: #8b949e;
}

:global(.dark-theme) .auth-link {
  color: #8b949e;
}

:global(.dark-theme) .link-primary {
  color: #58a6ff;
}

:global(.dark-theme) .link-primary:hover {
  color: #79c0ff;
}

:global(.dark-theme) .link-muted {
  color: #6e7681;
}

:global(.dark-theme) .link-muted:hover {
  color: #58a6ff;
}

:global(.dark-theme) .auth-submit-btn {
  background: #238636;
  box-shadow: 0 4px 15px rgba(35, 134, 54, 0.4);
}

:global(.dark-theme) .auth-submit-btn:hover {
  background: #2ea043;
  box-shadow: 0 6px 20px rgba(35, 134, 54, 0.5);
}

/* Dark theme login error styles */
:global(.dark-theme) .login-error {
  background: #2d1b1e;
  border-color: #5a2d2d;
  color: #ff7875;
}

/* Dark theme Element Plus overrides */
:global(.dark-theme) :deep(.el-input__wrapper) {
  background: #0d1117;
  border-color: #30363d;
  box-shadow: 0 2px 8px rgba(0,0,0,0.2);
}

:global(.dark-theme) :deep(.el-input__wrapper:hover) {
  border-color: #58a6ff;
  box-shadow: 0 2px 12px rgba(88, 166, 255, 0.15);
}

:global(.dark-theme) :deep(.el-input__wrapper.is-focus) {
  border-color: #58a6ff;
  box-shadow: 0 0 0 2px rgba(88, 166, 255, 0.2);
}

:global(.dark-theme) :deep(.el-input__inner) {
  background: transparent;
  color: #f0f6fc;
}

:global(.dark-theme) :deep(.el-input__inner::placeholder) {
  color: #6e7681;
}

/* Mobile dark theme adjustments */
@media (max-width: 768px) {
  :global(.dark-theme) .auth-section {
    background: #0d1117;
  }

  :global(.dark-theme) .auth-card {
    background: #161b22;
    border: 1px solid #30363d;
  }
}
</style>
