// frontend-react/pages/Login.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Eye, EyeOff, LogIn, Mail, Lock, Key, AlertCircle } from 'lucide-react'

export default function Login() {
  const navigate = useNavigate()
  const [showPassword, setShowPassword] = useState(false)
  const [loading, setLoading] = useState(false)
  const [loginError, setLoginError] = useState('')
  const [formData, setFormData] = useState({
    email: '',
    password: '',
  })

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    // 清除之前的错误信息
    setLoginError('')

    // 表单验证
    if (!formData.email || !formData.password) {
      setLoginError('请填写邮箱和密码')
      return
    }

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      setLoginError('请输入正确的邮箱格式')
      return
    }

    if (formData.password.length < 6) {
      setLoginError('密码长度不能少于6位')
      return
    }

    // 开始登录请求
    setLoading(true)

    try {
      // 模拟登录请求
      console.log('登录信息:', formData)

      // 这里应该调用实际的登录API
      // const response = await fetch('/api/v1/auth/login', {
      //   method: 'POST',
      //   headers: {
      //     'Content-Type': 'application/json',
      //   },
      //   body: JSON.stringify({
      //     email: formData.email,
      //     password: formData.password
      //   })
      // })

      // if (!response.ok) {
      //   throw new Error('登录失败')
      // }

      // const data = await response.json()

      // 模拟成功登录
      setTimeout(() => {
        setLoading(false)
        // 登录成功后跳转到首页
        navigate('/')
      }, 1000)

    } catch (error: any) {
      console.error('登录失败:', error)
      setLoading(false)

      // 错误处理
      if (error.response?.status === 401) {
        setLoginError('邮箱或密码错误，请重新输入')
      } else if (error.response?.data?.detail) {
        setLoginError(error.response.data.detail)
      } else {
        setLoginError('登录失败，请稍后重试')
      }
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    })

    // 清除错误信息
    if (loginError) {
      setLoginError('')
    }
  }

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !loading) {
      handleSubmit(e as any)
    }
  }

  return (
    <div className="min-h-screen bg-background overflow-hidden">
      <div className="flex h-screen">
        {/* 左侧品牌区域 (桌面端70%) */}
        <div className="hidden lg:flex lg:flex-1 lg:flex-col lg:justify-center lg:items-center bg-card p-16">
          <div className="text-center max-w-lg">
            <div className="mb-12">
              <div className="w-32 h-32 bg-muted rounded-full flex items-center justify-center mx-auto mb-8 border-4 border-primary">
                <Key className="w-16 h-16 text-primary" />
              </div>
              <h1 className="text-5xl font-bold text-card-foreground mb-4">agnets.app</h1>
            </div>

            <div className="mb-8">
              <h2 className="text-3xl font-semibold text-card-foreground mb-4">欢迎回来</h2>
              <p className="text-xl text-muted-foreground font-light">安全、高效的AI工具</p>
            </div>
          </div>
        </div>

        {/* 右侧登录区域 (桌面端30%) */}
        <div className="flex-1 lg:flex-none lg:w-1/3 flex items-center justify-center bg-popover p-8 lg:p-16 shadow-xl">
          <Card className="w-full max-w-md">
            <CardHeader className="text-center">
              <CardTitle className="text-2xl font-bold text-card-foreground">
                欢迎回来
              </CardTitle>
              <CardDescription className="text-muted-foreground">
                登录到您的agnets.app账户
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-6">
                {/* 邮箱输入 */}
                <div className="space-y-2">
                  <Label htmlFor="email" className="text-foreground">
                    邮箱地址
                  </Label>
                  <div className="relative">
                    <Mail className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-5 h-5" />
                    <Input
                      id="email"
                      name="email"
                      type="email"
                      placeholder="请输入邮箱地址"
                      value={formData.email}
                      onChange={handleChange}
                      onKeyPress={handleKeyPress}
                      className="pl-10 h-12 text-base focus:border-primary focus:ring-primary"
                      required
                    />
                  </div>
                </div>

                {/* 密码输入 */}
                <div className="space-y-2">
                  <Label htmlFor="password" className="text-foreground">
                    密码
                  </Label>
                  <div className="relative">
                    <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-5 h-5" />
                    <Input
                      id="password"
                      name="password"
                      type={showPassword ? 'text' : 'password'}
                      placeholder="请输入密码"
                      value={formData.password}
                      onChange={handleChange}
                      onKeyPress={handleKeyPress}
                      className="pl-10 pr-10 h-12 text-base focus:border-primary focus:ring-primary"
                      required
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="icon"
                      className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent text-muted-foreground hover:text-foreground"
                      onClick={() => setShowPassword(!showPassword)}
                    >
                      {showPassword ? (
                        <EyeOff className="h-5 w-5" />
                      ) : (
                        <Eye className="h-5 w-5" />
                      )}
                    </Button>
                  </div>
                </div>

                {/* 登录错误提示 */}
                {loginError && (
                  <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 flex items-center gap-3">
                    <AlertCircle className="w-5 h-5 text-destructive" />
                    <span className="text-destructive text-sm">
                      {loginError}
                    </span>
                  </div>
                )}

                {/* 登录按钮 */}
                <Button
                  type="submit"
                  className="w-full h-12 text-base font-semibold transition-all duration-300 hover:shadow-lg hover:-translate-y-0.5"
                  disabled={loading}
                >
                  {loading ? (
                    <>
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-current mr-2"></div>
                      登录中...
                    </>
                  ) : (
                    <>
                      <LogIn className="mr-2 h-4 w-4" />
                      登录
                    </>
                  )}
                </Button>
              </form>

              {/* 底部链接 */}
              <div className="mt-8 text-center space-y-4">
                <p className="text-muted-foreground text-sm">
                  还没有账户？
                  <Button
                    variant="link"
                    className="text-primary hover:text-primary/80 font-semibold px-1"
                    onClick={() => navigate('/register')}
                  >
                    立即注册
                  </Button>
                </p>
                <Button
                  variant="link"
                  className="text-muted-foreground hover:text-foreground text-sm"
                  onClick={() => navigate('/forgot-password')}
                >
                  忘记密码？
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/auth/Login.vue
<template>
  <div class="login-page">
    <div class="login-container">
      <!-- 左侧品牌展示区 (桌面端70%) -->
      <div class="brand-section">
        <div class="brand-content">
          <div class="brand-logo">
            <div class="logo-icon">
              <i class="fas fa-key"></i>
            </div>
            <h1 class="brand-title">agnets.app</h1>
          </div>

          <div class="brand-slogan">
            <h2>欢迎回来</h2>
            <p class="lead">安全、高效的AI工具</p>
          </div>
        </div>
      </div>

      <!-- 右侧登录表单区 (桌面端30%) -->
      <div class="auth-section">
        <div class="auth-card">
          <!-- 主题切换按钮 -->
          <div class="theme-toggle">
            <button @click="toggleTheme" class="theme-btn" :title="themeStore.isDark ? '切换到浅色模式' : '切换到深色模式'">
              <i :class="themeStore.isDark ? 'fas fa-sun' : 'fas fa-moon'"></i>
            </button>
          </div>

          <div class="auth-header">
            <h2 class="auth-title">欢迎回来</h2>
            <p class="auth-subtitle">登录到您的agnets.app账户</p>
          </div>

          <ElForm
            :model="loginForm"
            :rules="loginRules"
            ref="loginFormRef"
            @submit.prevent="handleLogin"
            class="auth-form"
          >
            <ElFormItem prop="email">
              <ElInput
                v-model="loginForm.email"
                placeholder="邮箱地址"
                type="email"
                size="large"
                :prefix-icon="ElIconUser"
                @keyup.enter="handleLogin"
                @input="clearLoginError"
              />
            </ElFormItem>

            <ElFormItem prop="password">
              <ElInput
                v-model="loginForm.password"
                placeholder="密码"
                type="password"
                size="large"
                :prefix-icon="ElIconLock"
                show-password
                @keyup.enter="handleLogin"
                @input="clearLoginError"
              />
            </ElFormItem>

            <!-- 登录错误提示 -->
            <div v-if="loginError" class="login-error" key="login-error">
              <i class="fas fa-exclamation-circle"></i>
              {{ loginError }}
            </div>

            <ElFormItem>
              <ElButton
                type="primary"
                size="large"
                class="auth-submit-btn"
                :loading="loading"
                @click="handleLogin"
              >
                登录
              </ElButton>
            </ElFormItem>
          </ElForm>

          <div class="auth-footer">
            <p class="auth-link">
              还没有账户？
              <router-link to="/register" class="link-primary">立即注册</router-link>
            </p>
            <router-link to="/forgot-password" class="link-muted">
              忘记密码？
            </router-link>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElForm, ElFormItem, ElInput, ElButton, ElMessage } from 'element-plus'
import { User as ElIconUser, Lock as ElIconLock } from '@element-plus/icons-vue'
import { useUserStore } from '../../store/user'
import { useThemeStore } from '../../store/theme'
import request from '../../utils/request'

const router = useRouter()
const route = useRoute()
const userStore = useUserStore()
const themeStore = useThemeStore()

const loading = ref(false)
const loginFormRef = ref()
const loginError = ref('')

const loginForm = reactive({
  email: '',
  password: ''
})

const loginRules = {
  email: [
    { required: true, message: '请输入邮箱地址', trigger: 'blur' },
    { type: 'email' as const, message: '请输入正确的邮箱格式', trigger: 'blur' }
  ],
  password: [
    { required: true, message: '请输入密码', trigger: 'blur' },
    { min: 6, message: '密码长度不能少于6位', trigger: 'blur' }
  ]
}

// 定义登录响应的类型
interface LoginResponse {
  user: {
    user_id: string
    email: string
    phone?: string
    is_active: boolean
    is_email_verified: boolean
    last_login_at?: string
    created_at: string
  }
  tokens: {
    access_token: string
    refresh_token: string
    token_type: string
    expires_in: number
  }
}

const handleLogin = async () => {
  if (!loginFormRef.value) return

  // 清除之前的错误信息
  loginError.value = ''

  // 先进行客户端表单验证
  try {
    await loginFormRef.value.validate()
  } catch (validationError) {
    // 表单验证失败，显示客户端校验错误提示
    loginError.value = '请检查表单填写是否正确'
    return
  }

  // 表单验证通过，开始登录请求
  loading.value = true

  try {
    const response: LoginResponse = await request.post('/api/v1/auth/login', {
      email: loginForm.email,
      password: loginForm.password
    })

    // 保存用户信息和token
    userStore.login({
      id: response.user.user_id,
      name: response.user.email,
      email: response.user.email,
      token: response.tokens.access_token,
      refreshToken: response.tokens.refresh_token
    })

    ElMessage.success('登录成功')

    // 根据用户是否有激活密钥决定跳转页面
    try {
      const hasActiveKeys = await userStore.hasActiveApiKeys()
      const redirectPath = hasActiveKeys ? '/dashboard' : '/key-activation'
      console.log(`用户登录成功，${hasActiveKeys ? '有激活密钥' : '无激活密钥'}，跳转到: ${redirectPath}`)
      router.push(redirectPath)
    } catch (error) {
      console.error('检查用户密钥状态失败:', error)
      // 如果检查失败，默认跳转到控制台
      router.push('/dashboard')
    }

  } catch (error: any) {
    console.error('登录失败:', error)

    // 服务器端登录错误处理 - 显示在表单上
    if (error.response?.status === 401) {
      loginError.value = '邮箱或密码错误，请重新输入'
    } else if (error.response?.data?.detail) {
      loginError.value = error.response.data.detail
    } else {
      loginError.value = '登录失败，请稍后重试'
    }
  } finally {
    loading.value = false
  }
}

const clearLoginError = () => {
  if (loginError.value) {
    loginError.value = ''
  }
}

const toggleTheme = () => {
  themeStore.toggleTheme()
  themeStore.saveThemePreference()
}

onMounted(() => {
  themeStore.initializeTheme()

  // 从URL参数获取邮箱（验证成功后传递）
  const email = route.query.email as string
  const verified = route.query.verified as string

  if (email) {
    loginForm.email = email

    if (verified === 'true') {
      ElMessage.success('邮箱验证成功！请输入密码登录')
    }
  }
})
</script>

<style scoped>
.login-page {
  height: 100vh;
  background: #f8f9fa;
  overflow: hidden;
}

.login-container {
  display: flex;
  height: 100vh;
}

/* 左侧品牌区域 (桌面端70%) */
.brand-section {
  flex: 0 0 70%;
  background: #2c3e50;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px;
  color: white;
  position: relative;
}

.brand-content {
  text-align: center;
  max-width: 600px;
  display: flex;
  flex-direction: column;
  justify-content: center;
  height: 100%;
}

.brand-logo {
  margin-bottom: 40px;
}

.logo-icon {
  width: 120px;
  height: 120px;
  background: #34495e;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 30px;
  border: 3px solid #3498db;
}

.logo-icon i {
  font-size: 48px;
  color: #3498db;
}

.brand-title {
  font-size: 3.5rem;
  font-weight: 700;
  margin: 0;
  letter-spacing: -1px;
  color: white;
}

.brand-slogan {
  margin-bottom: 0;
}

.brand-slogan h2 {
  font-size: 2rem;
  font-weight: 600;
  margin-bottom: 20px;
  color: #ecf0f1;
}

.brand-slogan .lead {
  font-size: 1.25rem;
  color: #bdc3c7;
  font-weight: 300;
}


/* 右侧登录区域 (桌面端30%) */
.auth-section {
  flex: 0 0 30%;
  background: #ffffff;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 60px 40px;
  box-shadow: -10px 0 30px rgba(0,0,0,0.1);
}

.auth-card {
  width: 100%;
  max-width: 400px;
  position: relative;
}

/* 主题切换按钮 */
.theme-toggle {
  position: absolute;
  top: 20px;
  right: 20px;
  z-index: 10;
}

.theme-btn {
  width: 40px;
  height: 40px;
  border: none;
  border-radius: 50%;
  background: #f8f9fa;
  color: #2c3e50;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

.theme-btn:hover {
  background: #e9ecef;
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.15);
}

.theme-btn i {
  font-size: 16px;
}

.auth-header {
  text-align: center;
  margin-bottom: 40px;
}

.auth-title {
  font-size: 2rem;
  font-weight: 700;
  color: #2c3e50;
  margin: 0 0 12px 0;
}

.auth-subtitle {
  font-size: 1rem;
  color: #7f8c8d;
  margin: 0;
}

.auth-form {
  margin-bottom: 30px;
}

.auth-form .el-form-item {
  margin-bottom: 24px;
}

/* 登录错误提示样式 */
.login-error {
  background: #fef0f0;
  border: 1px solid #fbc4c4;
  border-radius: 8px;
  padding: 12px 16px;
  margin-bottom: 20px;
  color: #f56565;
  font-size: 14px;
  display: flex;
  align-items: center;
  gap: 8px;
  position: relative;
  z-index: 10;
  transition: all 0.3s ease;
}

.login-error i {
  font-size: 16px;
}

.auth-submit-btn {
  width: 100%;
  height: 48px;
  font-size: 16px;
  font-weight: 600;
  border-radius: 8px;
  background: #3498db;
  border: none;
  box-shadow: 0 4px 15px rgba(52, 152, 219, 0.4);
  transition: all 0.3s ease;
}

.auth-submit-btn:hover {
  background: #2980b9;
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(52, 152, 219, 0.5);
}

.auth-footer {
  text-align: center;
}

.auth-link {
  margin: 0 0 15px 0;
  color: #7f8c8d;
  font-size: 14px;
}

.link-primary {
  color: #3498db;
  text-decoration: none;
  font-weight: 600;
  transition: color 0.3s ease;
}

.link-primary:hover {
  color: #2980b9;
  text-decoration: underline;
}

.link-muted {
  color: #95a5a6;
  text-decoration: none;
  font-size: 13px;
  transition: color 0.3s ease;
}

.link-muted:hover {
  color: #3498db;
  text-decoration: underline;
}

/* 平板端适配 (768px - 1024px) */
@media (max-width: 1024px) {
  .brand-section {
    flex: 0 0 60%;
    padding: 40px;
  }

  .auth-section {
    flex: 0 0 40%;
    padding: 40px 30px;
  }

  .brand-title {
    font-size: 2.5rem;
  }

  .brand-slogan h2 {
    font-size: 1.5rem;
  }

  .feature-item {
    padding: 20px;
    margin-bottom: 30px;
  }
}

/* 移动端适配 (隐藏品牌区域) */
@media (max-width: 768px) {
  .login-container {
    flex-direction: column;
  }

  .brand-section {
    display: none;
  }

  .auth-section {
    flex: 1;
    min-height: 100vh;
    padding: 40px 20px;
    background: #f8f9fa;
    box-shadow: none;
  }

  .auth-card {
    background: #ffffff;
    border-radius: 20px;
    padding: 40px 30px;
    box-shadow: 0 20px 40px rgba(0,0,0,0.1);
    border: 1px solid #e1e8ed;
  }

  .auth-title {
    color: #2c3e50;
  }

  .auth-subtitle {
    color: #5a6c7d;
  }
}

/* 小屏移动端 */
@media (max-width: 480px) {
  .auth-section {
    padding: 20px 15px;
  }

  .auth-card {
    padding: 30px 20px;
  }

  .auth-title {
    font-size: 1.5rem;
  }
}

/* 确保Element Plus组件样式 */
:deep(.el-input__wrapper) {
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.05);
  border: 1px solid #e1e8ed;
  transition: all 0.3s ease;
}

:deep(.el-input__wrapper:hover) {
  border-color: #3498db;
  box-shadow: 0 2px 12px rgba(52, 152, 219, 0.15);
}

:deep(.el-input__wrapper.is-focus) {
  border-color: #3498db;
  box-shadow: 0 0 0 2px rgba(52, 152, 219, 0.2);
}

:deep(.el-input__inner) {
  height: 48px;
  font-size: 15px;
}

:deep(.el-form-item__error) {
  margin-top: 8px;
}

/* Dark Theme Styles */
:global(.dark-theme) .login-page {
  background: #1a1a1a;
}

:global(.dark-theme) .brand-section {
  background: #0f1419;
}

:global(.dark-theme) .brand-title {
  color: #ffffff;
}

:global(.dark-theme) .brand-slogan h2 {
  color: #e1e8ed;
}

:global(.dark-theme) .brand-slogan .lead {
  color: #8b949e;
}


:global(.dark-theme) .auth-section {
  background: #161b22;
  box-shadow: -10px 0 30px rgba(0,0,0,0.3);
}

:global(.dark-theme) .auth-card {
  background: #0d1117;
  border: 1px solid #30363d;
}

:global(.dark-theme) .theme-btn {
  background: #21262d;
  color: #f0f6fc;
  box-shadow: 0 2px 8px rgba(0,0,0,0.3);
}

:global(.dark-theme) .theme-btn:hover {
  background: #30363d;
}

:global(.dark-theme) .auth-title {
  color: #f0f6fc;
}

:global(.dark-theme) .auth-subtitle {
  color: #8b949e;
}

:global(.dark-theme) .auth-link {
  color: #8b949e;
}

:global(.dark-theme) .link-primary {
  color: #58a6ff;
}

:global(.dark-theme) .link-primary:hover {
  color: #79c0ff;
}

:global(.dark-theme) .link-muted {
  color: #6e7681;
}

:global(.dark-theme) .link-muted:hover {
  color: #58a6ff;
}

:global(.dark-theme) .auth-submit-btn {
  background: #238636;
  box-shadow: 0 4px 15px rgba(35, 134, 54, 0.4);
}

:global(.dark-theme) .auth-submit-btn:hover {
  background: #2ea043;
  box-shadow: 0 6px 20px rgba(35, 134, 54, 0.5);
}

/* Dark theme login error styles */
:global(.dark-theme) .login-error {
  background: #2d1b1e;
  border-color: #5a2d2d;
  color: #ff7875;
}

/* Dark theme Element Plus overrides */
:global(.dark-theme) :deep(.el-input__wrapper) {
  background: #0d1117;
  border-color: #30363d;
  box-shadow: 0 2px 8px rgba(0,0,0,0.2);
}

:global(.dark-theme) :deep(.el-input__wrapper:hover) {
  border-color: #58a6ff;
  box-shadow: 0 2px 12px rgba(88, 166, 255, 0.15);
}

:global(.dark-theme) :deep(.el-input__wrapper.is-focus) {
  border-color: #58a6ff;
  box-shadow: 0 0 0 2px rgba(88, 166, 255, 0.2);
}

:global(.dark-theme) :deep(.el-input__inner) {
  background: transparent;
  color: #f0f6fc;
}

:global(.dark-theme) :deep(.el-input__inner::placeholder) {
  color: #6e7681;
}

/* Mobile dark theme adjustments */
@media (max-width: 768px) {
  :global(.dark-theme) .auth-section {
    background: #0d1117;
  }

  :global(.dark-theme) .auth-card {
    background: #161b22;
    border: 1px solid #30363d;
  }
}
</style>
