// frontend/src/views/admin/UserKeyUsageHistory.vue
<template>
  <div class="user-key-usage-history-page">
    <div class="container-fluid">
      <!-- 面包屑导航 -->
      <div class="breadcrumb-section">
        <ElBreadcrumb separator="/">
          <ElBreadcrumbItem @click="goToAdminDashboard" class="clickable">订阅管理</ElBreadcrumbItem>
          <ElBreadcrumbItem @click="goBack" class="clickable">订阅详情</ElBreadcrumbItem>
          <ElBreadcrumbItem>User Key使用履历</ElBreadcrumbItem>
        </ElBreadcrumb>
      </div>

      <!-- User Key基本信息 -->
      <div class="user-key-info-section">
        <ElCard shadow="never" class="info-card">
          <template #header>
            <div class="card-header">
              <h3>
                <i class="fas fa-key"></i>
                User Key信息
              </h3>
            </div>
          </template>

          <div v-if="loading.keyInfo" class="loading-container">
            <ElSkeleton :rows="2" animated />
          </div>

          <div v-else class="user-key-info">
            <ElDescriptions :column="3" border>
              <ElDescriptionsItem label="User Key">
                <code class="api-key-display">{{ apiKey }}</code>
              </ElDescriptionsItem>
              <ElDescriptionsItem label="所属用户">
                {{ keyInfo.user_email || '未激活' }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="状态">
                <ElTag :type="getStatusType(keyInfo.status)">
                  {{ getStatusText(keyInfo.status) }}
                </ElTag>
              </ElDescriptionsItem>
              <ElDescriptionsItem label="激活时间">
                {{ keyInfo.activation_date ? formatDate(keyInfo.activation_date) : '未激活' }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="过期时间">
                {{ keyInfo.expire_date ? formatDate(keyInfo.expire_date) : '-' }}
              </ElDescriptionsItem>
              <ElDescriptionsItem label="最后使用">
                {{ keyInfo.last_used_at ? formatDate(keyInfo.last_used_at) : '未使用' }}
              </ElDescriptionsItem>
            </ElDescriptions>
          </div>
        </ElCard>
      </div>

      <!-- 使用统计 -->
      <div class="usage-stats-section">
        <ElCard shadow="never" class="stats-card">
          <template #header>
            <div class="card-header">
              <h3>
                <i class="fas fa-chart-bar"></i>
                使用统计
              </h3>
              <ElButton @click="refreshStats" :loading="loading.stats">
                <i class="fas fa-sync-alt"></i>
                刷新
              </ElButton>
            </div>
          </template>

          <div v-if="loading.stats" class="loading-container">
            <ElSkeleton :rows="2" animated />
          </div>

          <div v-else class="stats-grid">
            <div class="stat-item">
              <div class="stat-icon requests">
                <i class="fas fa-exchange-alt"></i>
              </div>
              <div class="stat-content">
                <h4>{{ usageStats.total_requests || 0 }}</h4>
                <p>总请求次数</p>
              </div>
            </div>

            <div class="stat-item">
              <div class="stat-icon tokens">
                <i class="fas fa-coins"></i>
              </div>
              <div class="stat-content">
                <h4>{{ formatNumber(usageStats.total_tokens) || 0 }}</h4>
                <p>总Token数</p>
              </div>
            </div>

            <div class="stat-item">
              <div class="stat-icon credits">
                <i class="fas fa-gem"></i>
              </div>
              <div class="stat-content">
                <h4>{{ usageStats.total_credits_used || 0 }}</h4>
                <p>总积分消耗</p>
              </div>
            </div>

            <div class="stat-item">
              <div class="stat-icon services">
                <i class="fas fa-cogs"></i>
              </div>
              <div class="stat-content">
                <h4>{{ usageStats.unique_services || 0 }}</h4>
                <p>服务类型数</p>
              </div>
            </div>
          </div>
        </ElCard>
      </div>

      <!-- 使用记录列表 -->
      <div class="usage-records-section">
        <ElCard shadow="never" class="records-card">
          <template #header>
            <div class="card-header">
              <h3>
                <i class="fas fa-list"></i>
                使用记录
              </h3>
              <div class="header-actions">
                <ElButton @click="refreshRecords" :loading="loading.records">
                  <i class="fas fa-sync-alt"></i>
                  刷新
                </ElButton>
              </div>
            </div>
          </template>

          <!-- 筛选器 -->
          <div class="filter-section">
            <ElRow :gutter="20">
              <ElCol :span="6">
                <ElSelect
                  v-model="filters.service"
                  placeholder="服务类型筛选"
                  clearable
                  @change="applyFilters"
                >
                  <ElOption label="全部" value="" />
                  <ElOption
                    v-for="service in availableServices"
                    :key="service"
                    :label="service"
                    :value="service"
                  />
                </ElSelect>
              </ElCol>
              <ElCol :span="8">
                <ElDatePicker
                  v-model="filters.dateRange"
                  type="datetimerange"
                  range-separator="至"
                  start-placeholder="开始时间"
                  end-placeholder="结束时间"
                  format="YYYY-MM-DD HH:mm:ss"
                  value-format="YYYY-MM-DD HH:mm:ss"
                  @change="applyFilters"
                  clearable
                />
              </ElCol>
              <ElCol :span="4">
                <ElButton type="primary" @click="applyFilters">
                  <i class="fas fa-search"></i>
                  筛选
                </ElButton>
              </ElCol>
            </ElRow>
          </div>

          <!-- 使用记录表格 -->
          <div class="records-table">
            <ElTable
              v-loading="loading.records"
              :data="usageRecords"
              style="width: 100%"
            >
              <ElTableColumn prop="service" label="服务类型" width="200">
                <template #default="scope">
                  <ElTag type="info" size="small">
                    {{ scope.row.service }}
                  </ElTag>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="input_tokens" label="输入Token" width="120">
                <template #default="scope">
                  {{ formatNumber(scope.row.input_tokens) || '-' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="output_tokens" label="输出Token" width="120">
                <template #default="scope">
                  {{ formatNumber(scope.row.output_tokens) || '-' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="total_tokens" label="总Token" width="120">
                <template #default="scope">
                  {{ formatNumber(scope.row.total_tokens) || '-' }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="credits_used" label="积分消耗" width="100">
                <template #default="scope">
                  {{ scope.row.credits_used || 0 }}
                </template>
              </ElTableColumn>
              <ElTableColumn prop="remaining_credits" label="剩余积分" width="120">
                <template #default="scope">
                  <span v-if="scope.row.remaining_credits !== null && scope.row.remaining_credits !== undefined"
                        :class="getRemainingCreditsClass(scope.row.remaining_credits)">
                    {{ scope.row.remaining_credits }}
                  </span>
                  <span v-else class="text-muted">-</span>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="response_status" label="响应状态" width="100">
                <template #default="scope">
                  <ElTag :type="scope.row.response_status === 'success' ? 'success' : 'danger'" size="small">
                    {{ scope.row.response_status === 'success' ? '成功' : '失败' }}
                  </ElTag>
                </template>
              </ElTableColumn>
              <ElTableColumn prop="request_timestamp" label="请求时间" width="180">
                <template #default="scope">
                  {{ formatDate(scope.row.request_timestamp) }}
                </template>
              </ElTableColumn>
            </ElTable>
          </div>

          <!-- 分页 -->
          <div class="pagination-container">
            <ElPagination
              v-model:current-page="pagination.page"
              v-model:page-size="pagination.size"
              :page-sizes="[20, 50, 100]"
              :total="pagination.total"
              layout="total, sizes, prev, pager, next, jumper"
              @size-change="handleSizeChange"
              @current-change="handlePageChange"
            />
          </div>
        </ElCard>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  ElCard, ElButton, ElBreadcrumb, ElBreadcrumbItem, ElDescriptions, ElDescriptionsItem,
  ElTag, ElSkeleton, ElTable, ElTableColumn, ElSelect, ElOption, ElRow, ElCol,
  ElPagination, ElDatePicker
} from 'element-plus'
import request from '../../utils/request'

interface UsageRecord {
  id: number
  api_key_id: number
  service: string
  request_count: number
  credits_used: number
  remaining_credits?: number
  input_tokens?: number
  output_tokens?: number
  total_tokens?: number
  request_timestamp: string
  response_status?: string
  error_message?: string
}

interface UsageStats {
  total_requests: number
  total_tokens: number
  total_credits_used: number
  unique_services: number
  input_tokens: number
  output_tokens: number
  avg_tokens_per_request: number
  first_request: string
  last_request: string
}

interface KeyInfo {
  user_email?: string | null
  status: string
  activation_date?: string | null
  expire_date?: string | null
  last_used_at?: string | null
}

const route = useRoute()
const router = useRouter()

const apiKey = ref<string>('')
const keyInfo = ref<KeyInfo>({} as KeyInfo)
const usageRecords = ref<UsageRecord[]>([])
const usageStats = ref<UsageStats>({} as UsageStats)
const availableServices = ref<string[]>([])

const loading = reactive({
  keyInfo: false,
  stats: false,
  records: false
})

const filters = reactive({
  service: '',
  dateRange: null as [string, string] | null
})

const pagination = reactive({
  page: 1,
  size: 20,
  total: 0
})

// 获取API Key基本信息
const loadKeyInfo = async () => {
  try {
    loading.keyInfo = true

    // 尝试从用户密钥列表API获取信息
    const response: any = await request.get('/api/v1/admin/user-keys', {
      params: { api_key: apiKey.value }
    })

    if (response.user_keys && response.user_keys.length > 0) {
      const keyData = response.user_keys[0]
      keyInfo.value = {
        user_email: keyData.user_email,
        status: keyData.status,
        activation_date: keyData.activation_date,
        expire_date: keyData.expire_date,
        last_used_at: keyData.last_used_at
      }
    } else {
      // 如果找不到，使用默认值
      keyInfo.value = {
        user_email: '未激活',
        status: 'inactive',
        activation_date: null,
        expire_date: null,
        last_used_at: null
      }
    }
  } catch (error) {
    console.error('加载Key信息失败:', error)
    // 如果API调用失败，使用默认值
    keyInfo.value = {
      user_email: '加载失败',
      status: 'unknown',
      activation_date: null,
      expire_date: null,
      last_used_at: null
    }
    ElMessage.error('加载Key信息失败')
  } finally {
    loading.keyInfo = false
  }
}

// 获取使用统计
const loadUsageStats = async () => {
  try {
    loading.stats = true
    const params: any = {}
    if (filters.dateRange) {
      params.start_date = filters.dateRange[0]
      params.end_date = filters.dateRange[1]
    }

    const response: any = await request.get(`/api/v1/usage/stats`, {
      params: {
        api_key: apiKey.value,
        ...params
      }
    })
    usageStats.value = response
  } catch (error) {
    console.error('加载使用统计失败:', error)
    ElMessage.error('加载使用统计失败')
  } finally {
    loading.stats = false
  }
}

// 获取使用记录
const loadUsageRecords = async () => {
  try {
    loading.records = true
    const params: any = {
      api_key: apiKey.value,
      page: pagination.page,
      page_size: pagination.size
    }

    if (filters.service) {
      params.service = filters.service
    }

    if (filters.dateRange) {
      params.start_date = filters.dateRange[0]
      params.end_date = filters.dateRange[1]
    }

    const response: any = await request.get('/api/v1/usage/history', { params })
    usageRecords.value = response.records || []
    pagination.total = response.total || 0
  } catch (error) {
    console.error('加载使用记录失败:', error)
    ElMessage.error('加载使用记录失败')
  } finally {
    loading.records = false
  }
}

// 获取可用服务类型
const loadAvailableServices = async () => {
  try {
    const response: any = await request.get('/api/v1/usage/services', {
      params: { api_key: apiKey.value }
    })
    availableServices.value = response || []
  } catch (error) {
    console.error('加载服务类型失败:', error)
  }
}

// 应用筛选器
const applyFilters = () => {
  pagination.page = 1
  loadUsageRecords()
  loadUsageStats()
}

// 刷新统计
const refreshStats = () => {
  loadUsageStats()
}

// 刷新记录
const refreshRecords = () => {
  loadUsageRecords()
}

// 分页处理
const handlePageChange = (page: number) => {
  pagination.page = page
  loadUsageRecords()
}

const handleSizeChange = (size: number) => {
  pagination.size = size
  pagination.page = 1
  loadUsageRecords()
}

// 导航方法
const goBack = () => {
  router.go(-1)
}

const goToAdminDashboard = () => {
  router.push('/admin/dashboard')
}

// 工具函数
const formatDate = (dateString: string) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('zh-CN')
}

const formatNumber = (num: number) => {
  if (num == null) return '0'
  return num.toLocaleString()
}

const getStatusType = (status: string) => {
  switch (status) {
    case 'active': return 'success'
    case 'inactive': return 'warning'
    case 'expired': return 'danger'
    default: return 'info'
  }
}

const getStatusText = (status: string) => {
  switch (status) {
    case 'active': return '激活'
    case 'inactive': return '非激活'
    case 'expired': return '过期'
    default: return '未知'
  }
}

// 获取剩余积分样式类
const getRemainingCreditsClass = (remainingCredits: number) => {
  if (remainingCredits <= 0) return 'text-danger'
  if (remainingCredits <= 10) return 'text-warning'
  return 'text-success'
}

onMounted(() => {
  apiKey.value = route.params.apiKey as string
  if (apiKey.value) {
    loadKeyInfo()
    loadUsageStats()
    loadUsageRecords()
    loadAvailableServices()
  } else {
    ElMessage.error('缺少API Key参数')
    router.push('/admin/dashboard')
  }
})
</script>

<style scoped>
.user-key-usage-history-page {
  padding: 20px;
  background-color: #f5f7fa;
  min-height: 100vh;
}

.breadcrumb-section {
  margin-bottom: 20px;
}

.breadcrumb-section .clickable {
  cursor: pointer;
  color: #409eff;
}

.breadcrumb-section .clickable:hover {
  text-decoration: underline;
}

.user-key-info-section,
.usage-stats-section,
.usage-records-section {
  margin-bottom: 24px;
}

.info-card,
.stats-card,
.records-card {
  border: none;
  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-header h3 {
  margin: 0;
  font-size: 1.2rem;
  font-weight: 600;
  color: #2c3e50;
  display: flex;
  align-items: center;
  gap: 8px;
}

.header-actions {
  display: flex;
  gap: 12px;
}

.loading-container {
  padding: 20px;
}

.user-key-info {
  padding: 20px 0;
}

.api-key-display {
  background: #f5f7fa;
  padding: 4px 8px;
  border-radius: 4px;
  font-family: 'Monaco', 'Menlo', monospace;
  font-size: 12px;
  color: #606266;
}

.stats-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
  padding: 20px 0;
}

.stat-item {
  display: flex;
  align-items: center;
  gap: 15px;
  padding: 20px;
  background: #f8f9fa;
  border-radius: 8px;
  border-left: 4px solid #409eff;
}

.stat-icon {
  width: 50px;
  height: 50px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  font-size: 20px;
}

.stat-icon.requests { background: #3498db; }
.stat-icon.tokens { background: #f39c12; }
.stat-icon.credits { background: #e74c3c; }
.stat-icon.services { background: #27ae60; }

.stat-content h4 {
  font-size: 1.8rem;
  margin: 0;
  color: #2c3e50;
  font-weight: 700;
}

.stat-content p {
  margin: 4px 0 0 0;
  color: #7f8c8d;
  font-size: 14px;
}

.filter-section {
  margin-bottom: 20px;
  padding: 16px 0;
  border-bottom: 1px solid #f0f2f5;
}

.records-table {
  margin-bottom: 20px;
}


.text-danger {
  color: #f56c6c;
}

.text-warning {
  color: #e6a23c;
}

.text-success {
  color: #67c23a;
}

.text-muted {
  color: #909399;
}

.pagination-container {
  display: flex;
  justify-content: center;
  padding: 20px;
  border-top: 1px solid #f0f2f5;
}

/* 移动端适配 */
@media (max-width: 768px) {
  .user-key-usage-history-page {
    padding: 16px;
  }

  .card-header {
    flex-direction: column;
    gap: 12px;
  }

  .header-actions {
    width: 100%;
    justify-content: flex-end;
  }

  .stats-grid {
    grid-template-columns: 1fr;
  }
}

/* 深色主题支持 */
:global(.dark-theme) .user-key-usage-history-page {
  background-color: #0d1117;
}

:global(.dark-theme) .card-header h3 {
  color: #f0f6fc;
}

:global(.dark-theme) .api-key-display {
  background: #21262d;
  color: #f0f6fc;
}

:global(.dark-theme) .stat-item {
  background: #21262d;
}

:global(.dark-theme) .stat-content h4 {
  color: #f0f6fc;
}
</style>

// frontend-react/src/pages/admin/UserKeyUsageHistory.tsx
import React, { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import {
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbSeparator,
} from '@/components/ui/breadcrumb'
import {
  Pagination,
  PaginationContent,
  PaginationItem,
  PaginationPrevious,
  PaginationNext,
} from '@/components/ui/pagination'
import { ArrowLeft, Home } from 'lucide-react'
import request from '@/utils/request'
interface KeyInfo {
  user_email?: string | null
  status: string
  activation_date?: string | null
  expire_date?: string | null
  last_used_at?: string | null
}
interface UsageStats {
  total_requests: number
  total_tokens: number
  total_credits_used: number
  unique_services: number
  input_tokens: number
  output_tokens: number
  avg_tokens_per_request: number
  first_request: string
  last_request: string
}
interface UsageRecord {
  id: number
  api_key_id: number
  service: string
  request_count: number
  credits_used: number
  remaining_credits?: number
  input_tokens?: number
  output_tokens?: number
  total_tokens?: number
  request_timestamp: string
  response_status?: string
  error_message?: string
}
const UserKeyUsageHistory: React.FC = () => {
  const { apiKey } = useParams<{ apiKey: string }>()
  const navigate = useNavigate()
  const [keyInfo, setKeyInfo] = useState<KeyInfo | null>(null)
  const [usageStats, setUsageStats] = useState<UsageStats | null>(null)
  const [usageRecords, setUsageRecords] = useState<UsageRecord[]>([])
  const [availableServices, setAvailableServices] = useState<string[]>([])
  const [loading, setLoading] = useState({
    keyInfo: false,
    stats: false,
    records: false
  })
  const [errors, setErrors] = useState({
    keyInfo: '',
    stats: '',
    records: '',
    services: ''
  })
  const [filters, setFilters] = useState({
    service: 'all',
    startDate: '',
    endDate: ''
  })
  const [pagination, setPagination] = useState({
    page: 1,
    size: 20,
    total: 0
  })
  const loadKeyInfo = async () => {
    if (!apiKey) return
    try {
      setLoading(prev => ({ ...prev, keyInfo: true }))
      setErrors(prev => ({ ...prev, keyInfo: '' }))
      const response: any = await request.get('/admin/user-keys', {
        params: { api_key: apiKey }
      })
      // 适配不同的响应结构
      const userKeys = response.user_keys || response.data?.user_keys || []
      if (userKeys.length > 0) {
        const keyData = userKeys[0]
        setKeyInfo({
          user_email: keyData.user_email,
          status: keyData.status,
          activation_date: keyData.activation_date,
          expire_date: keyData.expire_date,
          last_used_at: keyData.last_used_at
        })
      } else {
        setKeyInfo({
          user_email: '未激活',
          status: 'inactive',
          activation_date: null,
          expire_date: null,
          last_used_at: null
        })
      }
    } catch (error) {
      console.error('加载Key信息失败:', error)
      setErrors(prev => ({ ...prev, keyInfo: '加载Key信息失败' }))
      setKeyInfo({
        user_email: '加载失败',
        status: 'unknown',
        activation_date: null,
        expire_date: null,
        last_used_at: null
      })
    } finally {
      setLoading(prev => ({ ...prev, keyInfo: false }))
    }
  }
  const loadUsageStats = async () => {
    if (!apiKey) return
    try {
      setLoading(prev => ({ ...prev, stats: true }))
      setErrors(prev => ({ ...prev, stats: '' }))
      const params: any = { api_key: apiKey }
      if (filters.startDate) params.start_date = filters.startDate
      if (filters.endDate) params.end_date = filters.endDate
      const response: any = await request.get(`/usage/stats`, { params })
      // 适配不同的响应结构
      const statsData = response.data || response
      setUsageStats(statsData)
    } catch (error) {
      console.error('加载使用统计失败:', error)
      setErrors(prev => ({ ...prev, stats: '加载使用统计失败' }))
      setUsageStats(null)
    } finally {
      setLoading(prev => ({ ...prev, stats: false }))
    }
  }
  const loadUsageRecords = async () => {
    if (!apiKey) return
    try {
      setLoading(prev => ({ ...prev, records: true }))
      setErrors(prev => ({ ...prev, records: '' }))
      const params: any = {
        api_key: apiKey,
        page: pagination.page,
        page_size: pagination.size
      }
      if (filters.service && filters.service !== 'all') params.service = filters.service
      if (filters.startDate) params.start_date = filters.startDate
      if (filters.endDate) params.end_date = filters.endDate
      const response: any = await request.get('/usage/history', { params })
      // 适配不同的响应结构
      const recordsData = response.records || response.data?.records || []
      const total = response.total || response.data?.total || 0
      setUsageRecords(recordsData)
      setPagination(prev => ({ ...prev, total }))
    } catch (err) {
      console.error('failed to load usage history', err)
      setErrors(prev => ({ ...prev, records: '加载使用记录失败' }))
      setUsageRecords([])
      setPagination(prev => ({ ...prev, total: 0 }))
    } finally {
      setLoading(prev => ({ ...prev, records: false }))
    }
  }
  const loadAvailableServices = async () => {
    if (!apiKey) return
    try {
      setErrors(prev => ({ ...prev, services: '' }))
      const response: any = await request.get('/usage/services', {
        params: { api_key: apiKey }
      })
      // 适配不同的响应结构
      const services = response.data || response || []
      setAvailableServices(services)
    } catch (error) {
      console.error('加载服务类型失败:', error)
      setErrors(prev => ({ ...prev, services: '加载服务类型失败' }))
      setAvailableServices([])
    }
  }
  const loadAllData = async () => {
    if (!apiKey) return
    await Promise.all([
      loadKeyInfo(),
      loadUsageStats(),
      loadUsageRecords(),
      loadAvailableServices()
    ])
  }
  const applyFilters = () => {
    setPagination(prev => ({ ...prev, page: 1 }))
    loadUsageRecords()
    loadUsageStats()
  }
  const refreshStats = () => {
    loadUsageStats()
  }
  const refreshRecords = () => {
    loadUsageRecords()
  }
  const handlePageChange = (page: number) => {
    setPagination(prev => ({ ...prev, page }))
  }
  const handleSizeChange = (size: number) => {
    setPagination(prev => ({ page: 1, size, total: prev.total }))
  }
  useEffect(() => {
    loadAllData()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [apiKey])
  useEffect(() => {
    loadUsageRecords()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pagination.page, pagination.size])
  const formatDate = (dateString: string) => {
    if (!dateString) return '-'
    return new Date(dateString).toLocaleString('zh-CN')
  }
  const formatNumber = (num: number) => {
    if (num == null) return '0'
    return num.toLocaleString()
  }
  const getStatusText = (status: string) => {
    switch (status) {
      case 'active': return '激活'
      case 'inactive': return '非激活'
      case 'expired': return '过期'
      default: return '未知'
    }
  }
  const getStatusVariant = (status: string) => {
    switch (status) {
      case 'active': return 'default'
      case 'inactive': return 'secondary'
      case 'expired': return 'destructive'
      default: return 'outline'
    }
  }
  return (
    <div className="min-h-screen bg-background p-6">
      {/* 面包屑导航 */}
      <div className="mb-6 space-y-4">
        <Breadcrumb>
          <BreadcrumbList>
            <BreadcrumbItem>
              <BreadcrumbLink href="/admin/dashboard" className="flex items-center gap-2">
                <Home className="h-4 w-4" />
                管理面板
              </BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink href="/admin/dashboard">用户密钥</BreadcrumbLink>
            </BreadcrumbItem>
            <BreadcrumbSeparator />
            <BreadcrumbItem>
              <BreadcrumbLink>使用履历</BreadcrumbLink>
            </BreadcrumbItem>
          </BreadcrumbList>
        </Breadcrumb>
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/admin/dashboard')}
            className="flex items-center gap-2"
          >
            <ArrowLeft size={18} />
            返回管理
          </Button>
          <h1 className="text-2xl font-bold text-foreground">User Key使用履历</h1>
        </div>
      </div>
      {/* User Key基本信息 */}
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            🔑 User Key信息
          </CardTitle>
        </CardHeader>
        <CardContent>
          {errors.keyInfo && (
            <Alert variant="destructive" className="mb-4">
              <AlertDescription>{errors.keyInfo}</AlertDescription>
            </Alert>
          )}
          {loading.keyInfo && <div className="text-center py-8 text-muted-foreground">加载中...</div>}
          {!loading.keyInfo && keyInfo ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div>
                <label className="text-sm text-muted-foreground">User Key</label>
                <div className="text-sm font-mono bg-muted px-2 py-1 rounded mt-1">
                  {apiKey}
                </div>
              </div>
              <div>
                <label className="text-sm text-muted-foreground">所属用户</label>
                <div className="text-lg font-semibold text-foreground">
                  {keyInfo.user_email || '未激活'}
                </div>
              </div>
              <div>
                <label className="text-sm text-muted-foreground">状态</label>
                <div className="mt-1">
                  <Badge variant={getStatusVariant(keyInfo.status)}>
                    {getStatusText(keyInfo.status)}
                  </Badge>
                </div>
              </div>
              <div>
                <label className="text-sm text-muted-foreground">激活时间</label>
                <div className="text-sm text-foreground">
                  {keyInfo.activation_date ? formatDate(keyInfo.activation_date) : '未激活'}
                </div>
              </div>
              <div>
                <label className="text-sm text-muted-foreground">过期时间</label>
                <div className="text-sm text-foreground">
                  {keyInfo.expire_date ? formatDate(keyInfo.expire_date) : '-'}
                </div>
              </div>
              <div>
                <label className="text-sm text-muted-foreground">最后使用</label>
                <div className="text-sm text-foreground">
                  {keyInfo.last_used_at ? formatDate(keyInfo.last_used_at) : '未使用'}
                </div>
              </div>
            </div>
          ) : (
            !loading.keyInfo && <div className="text-center py-8 text-muted-foreground">加载失败</div>
          )}
        </CardContent>
      </Card>
      {/* 使用统计 */}
      <Card className="mb-6">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              📊 使用统计
            </CardTitle>
            <Button
              onClick={refreshStats}
              disabled={loading.stats}
              variant="outline"
              size="sm"
            >
              {loading.stats ? '刷新中...' : '刷新'}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {errors.stats && (
            <Alert variant="destructive" className="mb-4">
              <AlertDescription>{errors.stats}</AlertDescription>
            </Alert>
          )}
          {loading.stats && <div className="text-center py-8 text-muted-foreground">加载中...</div>}
          {!loading.stats && usageStats ? (
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <Card className="border-l-4 border-blue-500">
                <CardContent className="p-4">
                  <div className="text-2xl font-bold text-blue-600">
                    {usageStats.total_requests || 0}
                  </div>
                  <div className="text-sm text-muted-foreground">总请求次数</div>
                </CardContent>
              </Card>
              <Card className="border-l-4 border-yellow-500">
                <CardContent className="p-4">
                  <div className="text-2xl font-bold text-yellow-600">
                    {formatNumber(usageStats.total_tokens) || 0}
                  </div>
                  <div className="text-sm text-muted-foreground">总Token数</div>
                </CardContent>
              </Card>
              <Card className="border-l-4 border-red-500">
                <CardContent className="p-4">
                  <div className="text-2xl font-bold text-red-600">
                    {usageStats.total_credits_used || 0}
                  </div>
                  <div className="text-sm text-muted-foreground">总积分消耗</div>
                </CardContent>
              </Card>
              <Card className="border-l-4 border-green-500">
                <CardContent className="p-4">
                  <div className="text-2xl font-bold text-green-600">
                    {usageStats.unique_services || 0}
                  </div>
                  <div className="text-sm text-muted-foreground">服务类型数</div>
                </CardContent>
              </Card>
            </div>
          ) : (
            !loading.stats && <div className="text-center py-8 text-muted-foreground">暂无数据</div>
          )}
        </CardContent>
      </Card>
      {/* 使用记录列表 */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              📋 使用记录
            </CardTitle>
            <Button
              onClick={refreshRecords}
              disabled={loading.records}
              variant="outline"
              size="sm"
            >
              {loading.records ? '刷新中...' : '刷新'}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {/* 错误显示 */}
          {(errors.records || errors.services) && (
            <Alert variant="destructive" className="mb-4">
              <AlertDescription>
                {errors.records && <div>{errors.records}</div>}
                {errors.services && <div>{errors.services}</div>}
              </AlertDescription>
            </Alert>
          )}
          {/* 筛选器 */}
          <div className="mb-6 p-4 border-b">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <Label htmlFor="service-filter">服务类型</Label>
                <Select
                  value={filters.service}
                  onValueChange={(value: string) => setFilters(prev => ({ ...prev, service: value }))}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="全部服务类型" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">全部</SelectItem>
                    {availableServices.map(service => (
                      <SelectItem key={service} value={service}>
                        {service}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="start-date">开始时间</Label>
                <Input
                  type="datetime-local"
                  id="start-date"
                  value={filters.startDate}
                  onChange={(e) => setFilters(prev => ({ ...prev, startDate: e.target.value }))}
                />
              </div>
              <div>
                <Label htmlFor="end-date">结束时间</Label>
                <Input
                  type="datetime-local"
                  id="end-date"
                  value={filters.endDate}
                  onChange={(e) => setFilters(prev => ({ ...prev, endDate: e.target.value }))}
                />
              </div>
              <div className="flex items-end">
                <Button onClick={applyFilters} className="w-full">
                  筛选
                </Button>
              </div>
            </div>
          </div>
          {loading.records && <div className="text-center py-8 text-muted-foreground">加载中...</div>}
          {!loading.records && usageRecords.length === 0 && (
            <div className="text-center py-8 text-muted-foreground">暂无记录</div>
          )}
          {!loading.records && usageRecords.length > 0 && (
            <div>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>服务类型</TableHead>
                    <TableHead>输入Token</TableHead>
                    <TableHead>输出Token</TableHead>
                    <TableHead>总Token</TableHead>
                    <TableHead>积分消耗</TableHead>
                    <TableHead>剩余积分</TableHead>
                    <TableHead>响应状态</TableHead>
                    <TableHead>请求时间</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {usageRecords.map((record) => (
                    <TableRow key={record.id}>
                      <TableCell>
                      <Badge variant="outline" className="text-xs">
                        {record.service}
                      </Badge>
                    </TableCell>
                      <TableCell>{formatNumber(record.input_tokens || 0) || '-'}</TableCell>
                      <TableCell>{formatNumber(record.output_tokens || 0) || '-'}</TableCell>
                      <TableCell>{formatNumber(record.total_tokens || 0) || '-'}</TableCell>
                      <TableCell>{record.credits_used || 0}</TableCell>
                      <TableCell>
                        {record.remaining_credits !== null && record.remaining_credits !== undefined ? (
                          <span className={record.remaining_credits <= 0 ? 'text-destructive font-semibold' :
                                           record.remaining_credits <= 10 ? 'text-orange-600 font-semibold' :
                                           'text-green-600'}>
                            {record.remaining_credits}
                          </span>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                      <TableCell>
                        <Badge
                          variant={record.response_status === 'success' ? 'default' : 'destructive'}
                          className="text-xs"
                        >
                          {record.response_status === 'success' ? '成功' : '失败'}
                        </Badge>
                      </TableCell>
                      <TableCell className="text-sm">
                        {formatDate(record.request_timestamp)}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
              {/* 分页 */}
              <div className="mt-6 flex items-center justify-between">
                <div className="text-sm text-muted-foreground">
                  共 {pagination.total} 条记录
                </div>
                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2">
                    <span className="text-sm text-muted-foreground">每页</span>
                    <Select
                      value={pagination.size.toString()}
                      onValueChange={(value: string) => handleSizeChange(Number(value))}
                    >
                      <SelectTrigger className="w-20">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="20">20</SelectItem>
                        <SelectItem value="50">50</SelectItem>
                        <SelectItem value="100">100</SelectItem>
                      </SelectContent>
                    </Select>
                    <span className="text-sm text-muted-foreground">条</span>
                  </div>
                  <Pagination>
                    <PaginationContent>
                      <PaginationItem>
                        <PaginationPrevious
                          onClick={() => handlePageChange(pagination.page - 1)}
                          className={pagination.page <= 1 ? 'pointer-events-none opacity-50' : 'cursor-pointer'}
                        />
                      </PaginationItem>
                      <PaginationItem>
                        <span className="text-sm text-muted-foreground px-4">
                          第 {pagination.page} 页
                        </span>
                      </PaginationItem>
                      <PaginationItem>
                        <PaginationNext
                          onClick={() => handlePageChange(pagination.page + 1)}
                          className={pagination.page * pagination.size >= pagination.total ? 'pointer-events-none opacity-50' : 'cursor-pointer'}
                        />
                      </PaginationItem>
                    </PaginationContent>
                  </Pagination>
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
export default UserKeyUsageHistory
