// frontend/src/views/KeyActivation.vue
<template>
  <div class="key-activation">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6">
          <div class="activation-card">
            <div class="text-center mb-4">
              <h2 class="fw-bold">用户Key激活</h2>
              <p class="text-muted">激活您的用户Key以使用服务</p>
            </div>

            <ElForm
              :model="activationForm"
              :rules="activationRules"
              ref="activationFormRef"
              label-width="0px"
            >
              <ElFormItem prop="userKey">
                <ElInput
                  v-model="activationForm.userKey"
                  placeholder="请输入要激活的用户Key"
                  size="large"
                  show-password
                />
                <div class="form-help">
                  <small class="text-muted">
                    输入您获得的用户Key，格式如：sk-xxxxxxxx...
                  </small>
                </div>
              </ElFormItem>

              <ElFormItem>
                <ElButton
                  type="primary"
                  size="large"
                  style="width: 100%"
                  :loading="loading"
                  @click="handleActivation"
                >
                  激活用户Key
                </ElButton>
              </ElFormItem>
            </ElForm>

            <div class="text-center mt-4">
              <router-link to="/dashboard" class="btn btn-outline-primary">
                返回控制台
              </router-link>
            </div>

            <!-- 激活成功对话框 -->
            <ElDialog
              v-model="showSuccessDialog"
              title="激活成功"
              width="500px"
              :show-close="false"
              :close-on-click-modal="false"
            >
              <div class="text-center">
                <ElIcon size="60" color="#67c23a" class="mb-3">
                  <ElIconCircleCheck />
                </ElIcon>
                <h4 class="mb-3">用户Key激活成功！</h4>

                <div class="key-info">
                  <p><strong>激活时间:</strong> {{ activatedKeyInfo.activationDate }}</p>
                  <p><strong>用户Key:</strong></p>
                  <ElInput
                    :value="activatedKeyInfo.userKey"
                    readonly
                    class="mb-3"
                  >
                    <template #append>
                      <ElButton @click="copyToClipboard(activatedKeyInfo.userKey)">
                        复制
                      </ElButton>
                    </template>
                  </ElInput>
                </div>

                <ElAlert
                  title="激活成功"
                  type="success"
                  description="您的用户Key已成功激活，现在可以使用服务了"
                  show-icon
                  :closable="false"
                />
              </div>

              <template #footer>
                <ElButton type="primary" @click="goToDashboard">
                  前往管理
                </ElButton>
              </template>
            </ElDialog>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import {
  ElForm,
  ElFormItem,
  ElInput,
  ElButton,
  ElAlert,
  ElDialog,
  ElIcon,
  ElMessage
} from 'element-plus'
import {
  CircleCheck as ElIconCircleCheck
} from '@element-plus/icons-vue'
import request from '../utils/request'

const router = useRouter()

const loading = ref(false)
const showSuccessDialog = ref(false)
const activationFormRef = ref()

const activationForm = reactive({
  userKey: ''
})

const activatedKeyInfo = reactive({
  userKey: '',
  activationDate: '',
  expireDate: '',
  credits: 0
})

const activationRules = {
  userKey: [
    { required: true, message: '请输入用户Key', trigger: 'blur' },
    { min: 10, message: '用户Key长度不能少于10位', trigger: 'blur' }
  ]
}

// 移除套餐状态检查相关代码

const handleActivation = async () => {
  if (!activationFormRef.value) return

  try {
    await activationFormRef.value.validate()

    loading.value = true

    await request.post('/api/v1/keys/activate-user-key', {
      user_key: activationForm.userKey
    })

    activatedKeyInfo.userKey = activationForm.userKey
    activatedKeyInfo.activationDate = new Date().toLocaleString('zh-CN')

    showSuccessDialog.value = true
    ElMessage.success('用户Key激活成功！')

    // 重置表单
    activationFormRef.value.resetFields()

  } catch (error: any) {
    console.error('激活失败:', error)

    if (error.response?.data?.detail) {
      ElMessage.error(error.response.data.detail)
    } else {
      ElMessage.error('激活失败，请稍后重试')
    }
  } finally {
    loading.value = false
  }
}

const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success('已复制到剪贴板')
  } catch (error) {
    ElMessage.error('复制失败')
  }
}

const goToDashboard = () => {
  showSuccessDialog.value = false
  // 激活成功后用户肯定有激活的密钥，直接跳转到控制台
  router.push('/dashboard')
}

// 移除页面加载时的套餐状态检查
</script>

<style scoped>
.key-activation {
  background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
  min-height: 100vh;
  padding: 50px 0;
}

.activation-card {
  background: white;
  padding: 40px;
  border-radius: 15px;
  box-shadow: 0 10px 30px rgba(0,0,0,0.1);
}

.form-help {
  margin-top: 5px;
}

.plan-info-card {
  margin-top: 20px;
}

.plan-details {
  display: flex;
  flex-direction: column;
  gap: 15px;
}

.detail-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.detail-item span {
  color: #666;
}

.key-info {
  background: #f8f9fa;
  padding: 20px;
  border-radius: 8px;
  margin: 20px 0;
  text-align: left;
}

.btn-outline-primary {
  border: 1px solid #409eff;
  color: #409eff;
  background: transparent;
  padding: 8px 20px;
  border-radius: 4px;
  text-decoration: none;
  transition: all 0.3s;
}

.btn-outline-primary:hover {
  background: #409eff;
  color: white;
}

/* 移动端优化 */
@media (max-width: 768px) {
  .key-activation {
    padding: 20px 0;
    background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
  }

  .activation-card {
    padding: 24px 20px;
    border-radius: 12px;
    margin: 0 16px;
    box-shadow: 0 4px 20px rgba(0,0,0,0.08);
  }

  .activation-card h2 {
    font-size: 1.5rem;
  }

  .activation-card .text-muted {
    font-size: 14px;
  }

  .form-help small {
    font-size: 12px;
  }

  .key-info {
    padding: 16px;
    margin: 16px 0;
  }

  .btn-outline-primary {
    width: 100%;
    padding: 12px 20px;
    font-size: 14px;
    min-height: 44px;
  }

  /* 表单输入框移动端优化 */
  .el-input__inner {
    font-size: 16px;
    min-height: 44px;
  }

  .el-button {
    min-height: 44px;
    font-size: 16px;
  }

  /* 对话框移动端优化 */
  .el-dialog {
    width: 90% !important;
    max-width: 400px;
  }
}
</style>

// frontend-react/src/pages/KeyActivation.tsx
import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { CheckCircle, AlertCircle } from 'lucide-react'
import { useUserStore } from '@/store/user'
import request from '@/utils/request'

interface ActivationForm {
  userKey: string
}

interface ToastMessage {
  type: 'success' | 'error'
  message: string
}

const KeyActivation: React.FC = () => {
  const navigate = useNavigate()
  const { isLoggedIn } = useUserStore()

  const [formData, setFormData] = useState<ActivationForm>({
    userKey: ''
  })
  const [loading, setLoading] = useState(false)
  const [showSuccessDialog, setShowSuccessDialog] = useState(false)
  const [toastMessage, setToastMessage] = useState<ToastMessage | null>(null)
  const [activatedKeyInfo, setActivatedKeyInfo] = useState({
    userKey: '',
    activationDate: '',
    expireDate: '',
    credits: 0
  })

  // 检查用户认证状态
  useEffect(() => {
    if (!isLoggedIn) {
      navigate('/login')
    }
  }, [isLoggedIn, navigate])

  // Toast 通知自动隐藏
  useEffect(() => {
    if (toastMessage) {
      const timer = setTimeout(() => {
        setToastMessage(null)
      }, 3000)
      return () => clearTimeout(timer)
    }
  }, [toastMessage])

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({ ...prev, [name]: value }))
  }

  const validateForm = (): boolean => {
    if (!formData.userKey.trim()) {
      setToastMessage({ type: 'error', message: '请输入用户Key' })
      return false
    }

    if (formData.userKey.length < 10) {
      setToastMessage({ type: 'error', message: '用户Key长度不能少于10位' })
      return false
    }

    return true
  }

  const handleActivation = async (e: React.FormEvent) => {
    e.preventDefault()

    if (!validateForm()) {
      return
    }

    setLoading(true)

    try {
      const res: any = await request.post('/keys/activate-user-key', {
        user_key: formData.userKey
      })

      setActivatedKeyInfo({
        userKey: formData.userKey,
        activationDate: new Date().toLocaleString('zh-CN'),
        expireDate: '',
        credits: 0
      })

      setShowSuccessDialog(true)
      setToastMessage({ type: 'success', message: res?.message || '用户Key激活成功！' })
      setFormData({ userKey: '' })

    } catch (error: any) {
      console.error('激活失败:', error)

      let errorMessage = '激活失败，请稍后重试'
      if (error.response?.data?.detail) {
        errorMessage = error.response.data.detail
      } else if (error.response?.data?.message) {
        errorMessage = error.response.data.message
      } else if (error.message) {
        errorMessage = error.message
      }

      setToastMessage({ type: 'error', message: errorMessage })
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text)
      setToastMessage({ type: 'success', message: '已复制到剪贴板' })
    } catch (error) {
      setToastMessage({ type: 'error', message: '复制失败' })
    }
  }

  const goToDashboard = () => {
    setShowSuccessDialog(false)
    navigate('/app/dashboard')
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-primary/10 to-primary/20 py-12 px-4">
      {/* Toast 通知 */}
      {toastMessage && (
        <div className={`fixed top-4 right-4 z-50 p-4 rounded-lg shadow-lg flex items-center gap-3 animate-in fade-in slide-in-from-top-2 ${
          toastMessage.type === 'success' 
            ? 'bg-green-500 text-white' 
            : 'bg-red-500 text-white'
        }`}>
          {toastMessage.type === 'success' ? (
            <CheckCircle size={20} />
          ) : (
            <AlertCircle size={20} />
          )}
          <span>{toastMessage.message}</span>
        </div>
      )}

      <div className="max-w-md mx-auto">
        <Card className="bg-white/95 backdrop-blur-sm border-0 shadow-xl">
          <CardHeader className="text-center pb-6">
            <CardTitle className="text-2xl font-bold text-gray-900">
              用户Key激活
            </CardTitle>
            <p className="text-gray-600 mt-2">激活您的用户Key以使用服务</p>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleActivation} className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="userKey" className="text-gray-700">
                  用户Key
                </Label>
                <Input
                  id="userKey"
                  name="userKey"
                  type="text"
                  placeholder="请输入要激活的用户Key"
                  value={formData.userKey}
                  onChange={handleInputChange}
                  className="h-12 text-base border-gray-200 focus:border-primary focus:ring-primary"
                />
                <div className="text-sm text-gray-500 mt-1">
                  输入您获得的用户Key，格式如：sk-xxxxxxxx...
                </div>
              </div>

              <Button
                type="submit"
                className="w-full h-12 text-base font-semibold bg-gradient-to-r from-primary to-primary/80 hover:from-primary hover:to-primary/90 border-0 shadow-lg hover:shadow-xl transition-all duration-300"
                disabled={loading}
              >
                {loading ? '激活中...' : '激活用户Key'}
              </Button>
            </form>

            <div className="text-center mt-6">
              <Button
                variant="outline"
                onClick={() => navigate('/app/dashboard')}
                className="border-primary text-primary hover:bg-primary hover:text-primary-foreground"
              >
                返回控制台
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* 激活成功对话框 */}
      <Dialog open={showSuccessDialog} onOpenChange={setShowSuccessDialog}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle className="text-center">激活成功</DialogTitle>
          </DialogHeader>

          <div className="text-center">
            <CheckCircle className="w-16 h-16 text-green-500 mx-auto mb-4" />
            <h4 className="text-lg font-semibold mb-4">用户Key激活成功！</h4>

            <div className="bg-gray-50 rounded-lg p-4 mb-4 text-left">
              <p><strong>激活时间:</strong> {activatedKeyInfo.activationDate}</p>
              <p className="mt-2"><strong>用户Key:</strong></p>
              <div className="flex gap-2 mt-2">
                <Input
                  value={activatedKeyInfo.userKey}
                  readOnly
                  className="flex-1"
                />
                <Button
                  onClick={() => copyToClipboard(activatedKeyInfo.userKey)}
                  variant="outline"
                >
                  复制
                </Button>
              </div>
            </div>

            <Alert className="bg-green-50 border-green-200">
              <CheckCircle className="h-4 w-4 text-green-600" />
              <AlertTitle className="text-green-800">激活成功</AlertTitle>
              <AlertDescription className="text-green-700">
                您的用户Key已成功激活，现在可以使用服务了
              </AlertDescription>
            </Alert>
          </div>

          <DialogFooter>
            <Button
              type="button"
              onClick={goToDashboard}
              className="w-full bg-gradient-to-r from-primary to-primary/80 hover:from-primary hover:to-primary/90"
            >
              前往管理
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

export default KeyActivation
