// frontend-react/src/pages/Dashboard.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useOutletContext } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useUserStore } from '@/store/user';
import request from '@/utils/request';
import JSZip from 'jszip';
import GettingStarted from '@/components/dashboard/GettingStarted'
import SubscriptionPlans from '@/components/dashboard/SubscriptionPlans'

interface ApiKey {
  id?: string;
  user_key_id: string;
  key_name: string;
  api_key: string;
  is_active: boolean;
  usage_count?: number;
  last_used_at?: string;
  created_at: string;
  package_name?: string;
  activation_date?: string;
  expire_date?: string;
  remaining_days?: number;
  status?: string;
  total_credits?: number;
  remaining_credits?: number;
}

// interface PlanInfo {
//   has_active_plan: boolean;
//   plan_type: string;
//   credits_remaining: number;
//   total_credits: number;
//   usage_percentage: number;
// }

interface DashboardContext {
  activeTab: string;
  setActiveTab: (tab: string) => void;
}

// Utility functions
const maskApiKey = (apiKey: string) => {
  if (!apiKey) return '-';
  if (apiKey.length <= 8) return apiKey;
  return apiKey.substring(0, 4) + '****' + apiKey.substring(apiKey.length - 4);
};

const getStatusClass = (status?: string) => {
  switch (status) {
    case 'active':
      return 'bg-green-100 text-green-800';
    case 'expired':
      return 'bg-red-100 text-red-800';
    case 'inactive':
    default:
      return 'bg-gray-100 text-gray-800';
  }
};

const getStatusText = (status?: string) => {
  switch (status) {
    case 'active':
      return '激活';
    case 'expired':
      return '过期';
    case 'inactive':
    default:
      return '未激活';
  }
};

const getProgressColor = (percentage: number) => {
  if (percentage > 50) return 'bg-green-500';
  if (percentage > 20) return 'bg-yellow-500';
  return 'bg-red-500';
};

const formatDateShort = (dateStr?: string) => {
  if (!dateStr) return '-';
  return new Date(dateStr).toLocaleDateString('zh-CN');
};

const getRemainingDaysClass = (days?: number) => {
  if (days === undefined || days === null) return 'text-muted-foreground';
  if (days <= 3) {
    return 'text-red-600 font-bold';
  } else if (days <= 7) {
    return 'text-yellow-600 font-bold';
  }
  return 'text-green-600';
};

const getRemainingCreditsClass = (remainingCredits?: number, totalCredits?: number) => {
  if (remainingCredits === undefined || totalCredits === undefined) return 'text-muted-foreground';
  if (!totalCredits || totalCredits <= 0) {
    return 'text-muted-foreground';
  }

  const percentage = (remainingCredits / totalCredits) * 100;

  if (percentage <= 10) {
    return 'text-red-600 font-bold';
  } else if (percentage <= 30) {
    return 'text-yellow-600 font-bold';
  }
  return 'text-green-600';
};

const copyApiKey = async (apiKey: string) => {
  try {
    await navigator.clipboard.writeText(apiKey);
    alert('API密钥已复制到剪贴板');
  } catch (error) {
    alert('复制失败，请手动复制');
  }
};

// 下载配置函数
const downloadConfig = async (key: any) => {
  try {
    // 检查key对象是否有有效的ID
    const keyId = key.id || key.user_key_id;
    if (!keyId) {
      alert('密钥ID无效，无法下载配置');
      return;
    }

    console.log('下载配置请求 - 密钥ID:', keyId);
    const response: any = await request.get(`/keys/${keyId}/download-config`);
    console.log('下载配置响应:', response);

    if (response.config && response.filename) {
      // 创建 settings.json
      const settingsBlob = new Blob([JSON.stringify(response.config, null, 2)], {
        type: 'application/json'
      });

      // 创建 config.json - 基于 settings_template.json 的结构
      const configData = {
        primaryApiKey: key.api_key
      };
      const configBlob = new Blob([JSON.stringify(configData, null, 2)], {
        type: 'application/json'
      });

      // 创建ZIP文件
      const zip = new JSZip();
      zip.file('settings.json', settingsBlob);
      zip.file('config.json', configBlob);

      // 生成ZIP文件
      const zipBlob = await zip.generateAsync({type: 'blob'});

      // 创建下载链接
      const url = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'claude-code-config.zip';
      document.body.appendChild(a);
      a.click();

      // 清理
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      alert('配置文件下载成功，包含 settings.json 和 config.json');
    } else {
      alert('下载失败：响应数据格式错误');
    }
  } catch (error: any) {
    console.error('下载配置失败:', error);

    // 改进错误处理
    let message = '下载设置文件失败';
    if (error?.response?.data?.detail) {
      message = error.response.data.detail;
    } else if (error?.response?.data?.message) {
      message = error.response.data.message;
    } else if (error?.message) {
      message = error.message;
    }

    alert(message);
  }
};

const Dashboard: React.FC = () => {
  const navigate = useNavigate();
  const { user, isLoggedIn } = useUserStore();
  const { activeTab, setActiveTab } = useOutletContext<DashboardContext>();
  const [apiKeys, setApiKeys] = useState<ApiKey[]>([]);
  const [loadingKeys, setLoadingKeys] = useState(false);
  const [keyStats, setKeyStats] = useState({ active: 0 });

  const [selectedApiKey, setSelectedApiKey] = useState<ApiKey | null>(null);
  const [usageRecords, setUsageRecords] = useState<any[]>([]);
  const [loadingUsageRecords, setLoadingUsageRecords] = useState(false);

  // 重置积分相关状态
  const [resetCreditsDialogVisible, setResetCreditsDialogVisible] = useState(false);
  const [resettingCredits, setResettingCredits] = useState(false);
  const [resetCreditsKey, setResetCreditsKey] = useState<ApiKey | null>(null);

  console.log('Dashboard组件开始渲染', { user, isLoggedIn });

  // 检查用户认证状态
  useEffect(() => {
    if (!isLoggedIn) {
      navigate('/login');
    }
  }, [isLoggedIn, navigate]);

  // 加载用户密钥
  const loadUserKeys = async () => {
    try {
      setLoadingKeys(true);
      const response: any = await request.get('/keys/');
      setApiKeys(response.keys || []);

      // 更新统计数据
      const activeCount = (response.keys || []).filter((k: ApiKey) => k.status === 'active').length;
      setKeyStats({ active: activeCount });
    } catch (error) {
      console.error('获取密钥列表失败:', error);
    } finally {
      setLoadingKeys(false);
    }
  };



  // 加载使用记录
  const loadUsageRecords = async () => {
    if (!selectedApiKey) return;

    try {
      setLoadingUsageRecords(true);
      console.log('正在加载使用记录，API Key:', selectedApiKey.api_key);

      // 使用正确的API路径和参数格式
      const response: any = await request.get('/usage/history', {
        params: {
          api_key: selectedApiKey.api_key,
          page: 1,
          page_size: 20
        }
      });

      setUsageRecords(response.records || []);
      console.log('使用记录加载完成:', response.records?.length || 0, '条记录');
    } catch (error) {
      console.error('获取使用记录失败:', error);
      setUsageRecords([]);
    } finally {
      setLoadingUsageRecords(false);
    }
  };

  useEffect(() => {
    if (isLoggedIn) {
      loadUserKeys();
    }
  }, [isLoggedIn]);

  // 当切换到使用历史标签页时加载使用记录
  useEffect(() => {
    if (activeTab === 'usage-history' && selectedApiKey) {
      loadUsageRecords();
    }
  }, [activeTab, selectedApiKey]);

  // 重置积分相关函数
  const resetCredits = (key: any) => {
    setResetCreditsKey(key);
    setResetCreditsDialogVisible(true);
  };

  // 确认重置积分
  const confirmResetCredits = async () => {
    if (!resetCreditsKey) return;

    try {
      setResettingCredits(true);

      // 检查key对象是否有有效的ID
      const keyId = resetCreditsKey.id || resetCreditsKey.user_key_id;
      if (!keyId) {
        alert('密钥ID无效，无法重置积分');
        return;
      }

      console.log('重置积分请求 - 密钥ID:', keyId);
      const response = await request.put(`/keys/${keyId}/reset-credits`);
      console.log('重置积分响应:', response);

      // 重新加载密钥列表以更新显示
      await loadUserKeys();

      // 安全地访问响应数据
      const message = response?.data?.message || '积分重置成功';
      alert(message);

      // 关闭弹窗
      setResetCreditsDialogVisible(false);
      setResetCreditsKey(null);
    } catch (error: any) {
      console.error('重置积分失败:', error);

      // 改进错误处理
      let message = '重置失败';
      if (error?.response?.data?.detail) {
        message = error.response.data.detail;
      } else if (error?.response?.data?.message) {
        message = error.response.data.message;
      } else if (error?.message) {
        message = error.message;
      }

      alert(message);
    } finally {
      setResettingCredits(false);
    }
  };

  // 处理重置积分取消
  const handleResetCreditsCancel = () => {
    setResetCreditsKey(null);
    setResetCreditsDialogVisible(false);
  };

  const renderKeysTab = () => (
    <div className="space-y-6">
      {/* 页面标题和操作按钮 */}
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold">API密钥一览</h2>
        <div className="flex space-x-2">
          <Button onClick={() => navigate('/key-activation')}>
            激活新密钥
          </Button>
          <Button variant="outline" onClick={loadUserKeys} disabled={loadingKeys}>
            刷新
          </Button>
        </div>
      </div>

      {/* 密钥统计 */}
      <div className="flex space-x-4">
        <div className="flex items-center space-x-2 p-3 bg-primary/10 rounded-lg">
          <div className="text-primary">🔑</div>
          <div>
            <div className="text-lg font-bold">{keyStats.active}</div>
            <div className="text-sm text-muted-foreground">激活密钥</div>
          </div>
        </div>
      </div>

      {/* API密钥表格 */}
      <Card>
        <CardContent className="p-0">
          {loadingKeys ? (
            <div className="text-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
              <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
            </div>
          ) : apiKeys.length === 0 ? (
            <div className="text-center py-8">
              <div className="text-muted-foreground mb-4">
                <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">暂无密钥</h3>
              <p className="text-sm text-muted-foreground mb-4">
                您还没有创建任何API密钥
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-1/4">订阅名称</TableHead>
                    <TableHead className="w-1/4">API密钥</TableHead>
                    <TableHead className="w-20">状态</TableHead>
                    <TableHead className="w-32">激活时间</TableHead>
                    <TableHead className="w-32">过期时间</TableHead>
                    <TableHead className="w-24">剩余天数</TableHead>
                    <TableHead className="w-1/4">操作</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {apiKeys.map((key) => (
                    <React.Fragment key={key.user_key_id}>
                      {/* 第一行：主要信息 */}
                      <TableRow>
                        <TableCell>
                          <div className="font-medium">
                            {key.package_name || '未知订阅'}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center space-x-2">
                            <code className="text-sm bg-muted px-2 py-1 rounded">
                              {maskApiKey(key.api_key)}
                            </code>
                            <Button
                              variant="ghost"
                              size="sm"
                              onClick={() => copyApiKey(key.api_key)}
                            >
                              复制
                            </Button>
                          </div>
                        </TableCell>
                        <TableCell>
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusClass(key.status)}`}>
                            {getStatusText(key.status)}
                          </span>
                        </TableCell>
                        <TableCell>
                          <span className="text-sm">
                            {key.activation_date ? formatDateShort(key.activation_date) : '未激活'}
                          </span>
                        </TableCell>
                        <TableCell>
                          <span className="text-sm">
                            {key.expire_date ? formatDateShort(key.expire_date) : '永久'}
                          </span>
                        </TableCell>
                        <TableCell>
                          <span className={`text-sm ${getRemainingDaysClass(key.remaining_days)}`}>
                            {key.remaining_days !== null ? `${key.remaining_days}天` : '永久'}
                          </span>
                        </TableCell>
                        <TableCell>
                          <div className="flex space-x-1">
                            <Button
                              size="sm"
                              onClick={() => {
                                console.log('点击履历按钮，API Key:', key.api_key);
                                setSelectedApiKey(key);
                                setActiveTab('usage-history');
                              }}
                            >
                              履历
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => resetCredits(key)}
                            >
                              重置积分
                            </Button>
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => downloadConfig(key)}
                            >
                              下载配置
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                      {/* 第二行：积分信息 */}
                      <TableRow>
                        <TableCell colSpan={7} className="bg-muted/50">
                          <div className="flex justify-between items-center py-2">
                            <div className="flex space-x-6 text-sm">
                              <div>
                                <span className="text-muted-foreground">总积分：</span>
                                <span>
                                  {key.total_credits !== null ? key.total_credits : '-'}
                                </span>
                              </div>
                              <div>
                                <span className="text-muted-foreground">剩余积分：</span>
                                <span className={getRemainingCreditsClass(key.remaining_credits, key.total_credits)}>
                                  {key.remaining_credits !== null ? key.remaining_credits : '-'}
                                </span>
                              </div>
                            </div>
                            {key.total_credits && key.total_credits > 0 && (
                              <div className="w-48">
                                <div className="flex justify-between text-sm mb-1">
                                  <span className="text-muted-foreground">剩余积分</span>
                                  <span>
                                    {Math.round(((key.remaining_credits || 0) / key.total_credits) * 100)}%
                                  </span>
                                </div>
                                <div className="w-full bg-gray-200 rounded-full h-2">
                                  <div
                                    className={`h-2 rounded-full ${getProgressColor(Math.round(((key.remaining_credits || 0) / key.total_credits) * 100))}`}
                                    style={{ width: `${Math.round(((key.remaining_credits || 0) / key.total_credits) * 100)}%` }}
                                  ></div>
                                </div>
                              </div>
                            )}
                          </div>
                        </TableCell>
                      </TableRow>
                    </React.Fragment>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );

  const renderGettingStartedTab = () => (
    <div className="space-y-6">
      <GettingStarted />
    </div>
  );

  const renderPackagesTab = () => (
    <SubscriptionPlans
      onDayCardClick={() => window.open('https://buy.example.com/day', '_blank')}
      onWeekCardClick={() => window.open('https://buy.example.com/week', '_blank')}
      onMonthCardClick={() => window.open('https://buy.example.com/month', '_blank')}
    />
  );

  const renderUsageHistoryTab = () => (
    <div className="space-y-6">
      {/* 返回按钮和标题 */}
      <div className="flex items-center space-x-4 mb-6">
        <Button
          variant="outline"
          onClick={() => {
            setActiveTab('keys');
            setSelectedApiKey(null);
          }}
        >
          ← 返回API密钥管理
        </Button>
        <h2 className="text-2xl font-bold">使用历史</h2>
      </div>

      {/* API密钥基本信息 */}
      {selectedApiKey && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center space-x-2">
              <span>🔑</span>
              <span>API密钥信息</span>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="font-medium text-muted-foreground">订阅名称:</span>
                <div className="mt-1">{selectedApiKey.package_name || '未知订阅'}</div>
              </div>
              <div>
                <span className="font-medium text-muted-foreground">API密钥:</span>
                <div className="mt-1">
                  <code className="bg-muted px-2 py-1 rounded text-sm">
                    {maskApiKey(selectedApiKey.api_key)}
                  </code>
                </div>
              </div>
              <div>
                <span className="font-medium text-muted-foreground">状态:</span>
                <div className="mt-1">
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${getStatusClass(selectedApiKey.status)}`}>
                    {getStatusText(selectedApiKey.status)}
                  </span>
                </div>
              </div>
              <div>
                <span className="font-medium text-muted-foreground">激活时间:</span>
                <div className="mt-1">
                  {selectedApiKey.activation_date ? new Date(selectedApiKey.activation_date).toLocaleString('zh-CN') : '未激活'}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* 使用记录表格 */}
      <Card>
        <CardHeader>
          <div className="flex justify-between items-center">
            <CardTitle className="flex items-center space-x-2">
              <span>📊</span>
              <span>使用记录</span>
            </CardTitle>
            <Button
              variant="outline"
              onClick={loadUsageRecords}
              disabled={loadingUsageRecords}
            >
              刷新
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {loadingUsageRecords ? (
            <div className="text-center py-8">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
              <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
            </div>
          ) : usageRecords.length === 0 ? (
            <div className="text-center py-8">
              <div className="text-muted-foreground mb-4">
                <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
              </div>
              <h3 className="text-lg font-medium text-gray-900 mb-2">暂无使用记录</h3>
              <p className="text-sm text-muted-foreground">
                该API密钥暂无使用记录
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-48">请求时间</TableHead>
                    <TableHead className="w-24">积分消耗</TableHead>
                    <TableHead className="w-32">剩余积分</TableHead>
                    <TableHead className="w-24">响应状态</TableHead>
                    <TableHead className="w-1/3">服务类型</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {usageRecords.map((record, index) => (
                    <TableRow key={index}>
                      <TableCell>
                        {record.request_timestamp ? new Date(record.request_timestamp).toLocaleString('zh-CN') : '-'}
                      </TableCell>
                      <TableCell>
                        {record.credits_used || 0}
                      </TableCell>
                      <TableCell>
                        {record.remaining_credits !== null && record.remaining_credits !== undefined ? (
                          <span className={getRemainingCreditsClass(record.remaining_credits, selectedApiKey?.total_credits)}>
                            {record.remaining_credits}
                          </span>
                        ) : (
                          <span className="text-muted-foreground">-</span>
                        )}
                      </TableCell>
                      <TableCell>
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          record.response_status === 'success' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                        }`}>
                          {record.response_status === 'success' ? '成功' : '失败'}
                        </span>
                      </TableCell>
                      <TableCell>
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-primary/20 text-primary">
                          {record.service}
                        </span>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );

  const renderTabContent = () => {
    switch (activeTab) {
      case 'keys':
        return renderKeysTab();
      case 'getting-started':
        return renderGettingStartedTab();
      case 'packages':
        return renderPackagesTab();
      case 'usage-history':
        return renderUsageHistoryTab();
      default:
        return renderKeysTab();
    }
  };

  return (
    <div className="p-6">
      {/* 页面标题 */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold tracking-tight">控制台</h1>
        <p className="text-muted-foreground">
          欢迎回来，{user?.name || '用户'}！管理您的API密钥和订阅
        </p>
      </div>

      {/* 标签页内容 */}
      <div>
        {renderTabContent()}
      </div>

      {/* 重置积分确认对话框 */}
      <Dialog open={resetCreditsDialogVisible} onOpenChange={setResetCreditsDialogVisible}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>确认重置积分</DialogTitle>
            <DialogDescription>
              您确定要重置此API密钥的积分吗？此操作将把积分恢复为初始值，无法撤销。
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            {resetCreditsKey && (
              <div className="text-sm text-muted-foreground">
                <p><strong>订阅名称:</strong> {resetCreditsKey.package_name || '未知订阅'}</p>
                <p><strong>API密钥:</strong> {maskApiKey(resetCreditsKey.api_key)}</p>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={handleResetCreditsCancel}
              disabled={resettingCredits}
            >
              取消
            </Button>
            <Button
              onClick={confirmResetCredits}
              disabled={resettingCredits}
            >
              {resettingCredits ? '重置中...' : '确认重置'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default Dashboard;

// frontend/src/views/Dashboard.vue
<template>
  <div class="dashboard">
    <!-- 移动端侧边栏 -->
    <MobileSidebar
      :show-mobile-sidebar="showMobileSidebar"
      :active-tab="activeTab"
      @close="showMobileSidebar = false"
      @tab-change="setActiveTab"
    />

    <div class="container-fluid">
      <div class="row">
        <!-- 桌面端侧边栏 -->
        <PCSidebar
          :active-tab="activeTab"
          @tab-change="handleTabChange"
        />

        <!-- 主内容区 -->
        <div class="col-12 col-md-9 col-lg-10 main-content">
          <!-- 移动端顶部栏 -->
          <div class="mobile-header d-md-none">
            <button class="mobile-menu-btn" @click="showMobileSidebar = true">
              <i class="fas fa-bars"></i>
            </button>
            <div class="mobile-title">
              {{ getCurrentTabTitle() }}
            </div>
          </div>

          <!-- API密钥管理 -->
          <ApiKeysManagement
            v-if="activeTab === 'keys'"
            :api-keys="apiKeys"
            :loading-keys="loadingKeys"
            :key-stats="keyStats"
            @refresh-keys="refreshKeys"
            @view-usage-history="viewUsageHistory"
            @reset-credits="resetCredits"
            @download-config="downloadConfig"
          />

          <!-- 安装Claude Code -->
          <div v-if="activeTab === 'getting-started'" class="tab-content">
            <h2 class="mb-4">安装Claude Code</h2>

            <!-- 系统要求 -->
            <SystemRequirements />

            <!-- 开发工具安装指南（可折叠） -->
            <ElCollapse v-model="activeCollapseItems" class="mb-4">
              <!-- Node.js安装指南 -->
              <ElCollapseItem name="nodejs" title="📦 Node.js 安装指南">
                <NodeJsInstallation />
              </ElCollapseItem>

              <!-- Git安装指南 -->
              <ElCollapseItem name="git" title="🔧 Git 安装指南">
                <GitInstallation />
              </ElCollapseItem>
            </ElCollapse>

            <!-- Claude Code安装方法 -->
            <ClaudeCodeInstallation />

            <!-- Claude Code安装验证 -->
            <InstallationVerification />


            <!-- 使用指南 -->
            <UsageGuide />

            <!-- VS Code插件安装 -->
            <VSCodeExtension />
          </div>

          <!-- 订阅一览 -->
          <SubscriptionPlans
            v-if="activeTab === 'packages'"
            @day-card-click="handleDayCardClick"
            @week-card-click="handleWeekCardClick"
            @month-card-click="handleMonthCardClick"
          />


          <!-- 推广计划 -->
          <PromotionPlan
            v-if="activeTab === 'promotion'"
            @get-promotion-link="handleGetPromotionLink"
            @view-promotion-rules="handleViewPromotionRules"
          />

          <!-- 使用履历 -->
          <UsageHistory
            v-if="activeTab === 'usage-history'"
            :selected-api-key="selectedApiKey"
            :usage-stats="usageStats"
            :usage-records="usageRecords"
            :loading-usage-records="loadingUsageRecords"
            :usage-pagination="usagePagination"
            @back-to-keys="activeTab = 'keys'"
            @refresh-usage-records="refreshUsageRecords"
            @usage-size-change="handleUsageSizeChange"
            @usage-page-change="handleUsagePageChange"
          />

          <!-- 重置积分确认弹窗 -->
          <template v-if="!isMobile">
            <ResetCreditsDialog
              v-model="resetCreditsDialogVisible"
              :key-data="resetCreditsKey"
              :loading="resettingCredits"
              @confirm="confirmResetCredits"
              @cancel="handleResetCreditsCancel"
            />
          </template>
          <template v-else>
            <MobileResetCreditsDialog
              v-model="resetCreditsDialogVisible"
              :key-data="resetCreditsKey"
              :loading="resettingCredits"
              @confirm="confirmResetCredits"
              @cancel="handleResetCreditsCancel"
            />
          </template>

          <!-- 资料中心 -->
          <ResourcesCenter
            v-if="activeTab === 'resources'"
            @go-to-best-practices="goToClaudeCodeBestPractices"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import JSZip from 'jszip'
import {
  ElMessage,
  ElCollapse,
  ElCollapseItem
} from 'element-plus'
import ResetCreditsDialog from '../components/ResetCreditsDialog.vue'
import MobileResetCreditsDialog from '../components/MobileResetCreditsDialog.vue'
import ResourcesCenter from '../components/ResourcesCenter.vue'
import PromotionPlan from '../components/PromotionPlan.vue'
import PCSidebar from '../components/dashboard/PCSidebar.vue'
import MobileSidebar from '../components/dashboard/MobileSidebar.vue'
import ApiKeysManagement from '../components/dashboard/ApiKeysManagement.vue'
import SubscriptionPlans from '../components/dashboard/SubscriptionPlans.vue'
import UsageHistory from '../components/dashboard/UsageHistory.vue'
import SystemRequirements from '../components/dashboard/SystemRequirements.vue'
import NodeJsInstallation from '../components/dashboard/NodeJsInstallation.vue'
import ClaudeCodeInstallation from '../components/dashboard/ClaudeCodeInstallation.vue'
import InstallationVerification from '../components/dashboard/InstallationVerification.vue'
import UsageGuide from '../components/dashboard/UsageGuide.vue'
import VSCodeExtension from '../components/dashboard/VSCodeExtension.vue'
import GitInstallation from '../components/dashboard/GitInstallation.vue'
import request from '../utils/request'
import '../styles/dashboard/index.css'

const router = useRouter()

// 控制折叠面板的展开项
const activeCollapseItems = ref<string[]>([])

interface ApiKey {
  id?: string
  user_key_id: string
  key_name: string
  api_key: string
  is_active: boolean
  usage_count?: number
  last_used_at?: string
  created_at: string
  package_name?: string
  activation_date?: string
  expire_date?: string
  remaining_days?: number
  status?: string
  total_credits?: number
  remaining_credits?: number
}

const activeTab = ref('keys')
const apiKeys = ref<ApiKey[]>([])
const filteredKeys = ref<ApiKey[]>([])
const loadingKeys = ref(false)
const selectedApiKey = ref<ApiKey | null>(null)
const showMobileSidebar = ref(false)

// 重置积分弹窗相关
const resetCreditsDialogVisible = ref(false)
const resettingCredits = ref(false)
const resetCreditsKey = ref<ApiKey | null>(null)

// 移动端检测
const isMobile = ref(false)

// 检测设备类型
const checkDeviceType = () => {
  isMobile.value = window.innerWidth < 768
}

const keyStats = reactive({
  active: 0
})



const planInfo = reactive({
  has_active_plan: false,
  plan_type: '免费套餐',
  credits_remaining: 0,
  total_credits: 0,
  usage_percentage: 0
})


// 使用履历相关数据
const usageStats = reactive({
  total_requests: 0,
  total_tokens: 0,
  total_credits_used: 0,
  unique_services: 0
})

const usageRecords = ref<any[]>([])
const availableServices = ref<string[]>([])
const loadingUsageStats = ref(false)
const loadingUsageRecords = ref(false)


const usagePagination = reactive({
  current: 1,
  size: 20,
  total: 0
})




const loadUserKeys = async () => {
  try {
    loadingKeys.value = true
    const response: any = await request.get('/api/v1/keys/')
    apiKeys.value = response.keys || []

    // 更新统计数据
    keyStats.active = apiKeys.value.filter(k => k.status === 'active').length

    filteredKeys.value = apiKeys.value
  } catch (error) {
    console.error('获取密钥列表失败:', error)
    ElMessage.error('获取密钥列表失败')
  } finally {
    loadingKeys.value = false
  }
}

const loadPlanStatus = async () => {
  try {
    const response = await request.get('/api/v1/keys/plan-status')
    Object.assign(planInfo, response.data)
  } catch (error) {
    console.error('获取套餐状态失败:', error)
    // 设置默认值确保页面能正常显示
    Object.assign(planInfo, {
      has_active_plan: false,
      plan_type: '无订阅',
      credits_remaining: 0,
      total_credits: 0,
      usage_percentage: 0
    })
    // 不显示错误提示，避免对没有API key的用户造成困扰
  }
}

// 已删除禁用/启用按钮，此函数暂时保留
// const toggleKeyStatus = async (key: any) => {
//   try {
//     await request.put(`/api/v1/keys/${key.id}/toggle`)
//     key.is_active = !key.is_active
//     ElMessage.success(`密钥已${key.is_active ? '启用' : '禁用'}`)
//   } catch (error) {
//     ElMessage.error('操作失败')
//   }
// }



// 重置积分 - 打开确认弹窗
const resetCredits = (key: any) => {
  resetCreditsKey.value = key
  resetCreditsDialogVisible.value = true
}

// 确认重置积分
const confirmResetCredits = async () => {
  if (!resetCreditsKey.value) return

  try {
    resettingCredits.value = true

    // 检查key对象是否有有效的ID
    const keyId = resetCreditsKey.value.id || resetCreditsKey.value.user_key_id
    if (!keyId) {
      ElMessage.error('密钥ID无效，无法重置积分')
      return
    }

    console.log('重置积分请求 - 密钥ID:', keyId)
    const response = await request.put(`/api/v1/keys/${keyId}/reset-credits`)
    console.log('重置积分响应:', response)

    // 重新加载密钥列表以更新显示
    await loadUserKeys()

    // 安全地访问响应数据
    const message = response?.data?.message || '积分重置成功'
    ElMessage.success(message)

    // 关闭弹窗
    resetCreditsDialogVisible.value = false
    resetCreditsKey.value = null
  } catch (error: any) {
    console.error('重置积分失败:', error)

    // 改进错误处理
    let message = '重置失败'
    if (error?.response?.data?.detail) {
      message = error.response.data.detail
    } else if (error?.response?.data?.message) {
      message = error.response.data.message
    } else if (error?.message) {
      message = error.message
    }

    ElMessage.error(message)
  } finally {
    resettingCredits.value = false
  }
}

// 处理重置积分取消
const handleResetCreditsCancel = () => {
  resetCreditsKey.value = null
}

// 处理获取推广链接
const handleGetPromotionLink = () => {
  ElMessage.info('推广计划功能即将上线，敬请期待！')
}

// 处理查看推广规则
const handleViewPromotionRules = () => {
  ElMessage.info('推广规则功能即将上线，敬请期待！')
}

// 下载设置文件
const downloadConfig = async (key: any) => {
  try {
    // 检查key对象是否有有效的ID
    const keyId = key.id || key.user_key_id
    if (!keyId) {
      ElMessage.error('密钥ID无效，无法下载配置')
      return
    }

    console.log('下载配置请求 - 密钥ID:', keyId)
    const response: any = await request.get(`/api/v1/keys/${keyId}/download-config`)
    console.log('下载配置响应:', response)

    if (response.config && response.filename) {
      // 创建 settings.json
      const settingsBlob = new Blob([JSON.stringify(response.config, null, 2)], {
        type: 'application/json'
      })

      // 创建 config.json - 基于 settings_template.json 的结构
      const configData = {
        primaryApiKey: key.api_key
      }
      const configBlob = new Blob([JSON.stringify(configData, null, 2)], {
        type: 'application/json'
      })

      // 创建ZIP文件
      const zip = new JSZip()
      zip.file('settings.json', settingsBlob)
      zip.file('config.json', configBlob)

      // 生成ZIP文件
      const zipBlob = await zip.generateAsync({type: 'blob'})

      // 创建下载链接
      const url = URL.createObjectURL(zipBlob)
      const a = document.createElement('a')
      a.href = url
      a.download = 'claude-code-config.zip'
      document.body.appendChild(a)
      a.click()

      // 清理
      document.body.removeChild(a)
      URL.revokeObjectURL(url)

      ElMessage.success('配置文件下载成功，包含 settings.json 和 config.json')
    } else {
      ElMessage.error('下载失败：响应数据格式错误')
    }
  } catch (error: any) {
    console.error('下载配置失败:', error)

    // 改进错误处理
    let message = '下载设置文件失败'
    if (error?.response?.data?.detail) {
      message = error.response.data.detail
    } else if (error?.response?.data?.message) {
      message = error.response.data.message
    } else if (error?.message) {
      message = error.message
    }

    ElMessage.error(message)
  }
}

// 新增的密钥管理方法
const refreshKeys = () => {
  loadUserKeys()
}

const goToClaudeCodeBestPractices = () => {
  router.push('/claude-code-best-practices')
}

// 处理订阅卡片点击事件
const handleDayCardClick = () => {
  // 跳转到日卡购买页面
  window.open('https://www.goofish.com/item?spm=a21ybx.personal.feeds.1.44016ac2aDwbw4&id=983395304846&categoryId=50023914', '_blank')
}

const handleWeekCardClick = () => {
  // 跳转到周卡购买页面
  window.open('https://www.goofish.com/item?spm=a21ybx.personal.feeds.1.44016ac2aDwbw4&id=983395304846&categoryId=50023914', '_blank')
}

const handleMonthCardClick = () => {
  // 跳转到月卡购买页面
  window.open('https://www.goofish.com/item?spm=a21ybx.personal.feeds.1.44016ac2aDwbw4&id=983395304846&categoryId=50023914', '_blank')
}



const viewUsageHistory = (key: any) => {
  // 在同一页面切换到使用履历标签
  activeTab.value = 'usage-history'
  selectedApiKey.value = key

  // 加载使用履历数据
  loadUsageStats()
  loadUsageRecords()
  loadAvailableServices()
}

// 已删除详情按钮，此函数暂时保留
// const viewKeyDetails = (key: any) => {
//   ElMessageBox.alert(
//     `
//     <div>
//       <p><strong>订阅名称:</strong> ${key.package_name || '未知订阅'}</p>
//       <p><strong>API密钥:</strong> ${key.api_key}</p>
//       <p><strong>状态:</strong> ${key.is_active ? '激活' : '禁用'}</p>
//       <p><strong>激活时间:</strong> ${formatDate(key.activation_date)}</p>
//       <p><strong>最后使用:</strong> ${key.last_used_at ? formatDate(key.last_used_at) : '从未使用'}</p>
//     </div>
//     `,
//     '密钥详情',
//     {
//       dangerouslyUseHTMLString: true,
//       confirmButtonText: '关闭'
//     }
//   )
// }



// 使用履历相关方法
const loadUsageStats = async () => {
  if (!selectedApiKey.value) return

  try {
    loadingUsageStats.value = true
    const params: any = {}

    const response: any = await request.get(`/api/v1/usage/stats`, {
      params: {
        api_key: selectedApiKey.value.api_key,
        ...params
      }
    })
    Object.assign(usageStats, response)
  } catch (error) {
    console.error('加载使用统计失败:', error)
    ElMessage.error('加载使用统计失败')
  } finally {
    loadingUsageStats.value = false
  }
}

const loadUsageRecords = async () => {
  if (!selectedApiKey.value) return

  try {
    loadingUsageRecords.value = true
    const params: any = {
      api_key: selectedApiKey.value.api_key,
      page: usagePagination.current,
      page_size: usagePagination.size
    }



    const response: any = await request.get('/api/v1/usage/history', { params })
    usageRecords.value = response.records || []
    usagePagination.total = response.total || 0
  } catch (error) {
    console.error('加载使用记录失败:', error)
    ElMessage.error('加载使用记录失败')
  } finally {
    loadingUsageRecords.value = false
  }
}

const loadAvailableServices = async () => {
  if (!selectedApiKey.value) return

  try {
    const response: any = await request.get('/api/v1/usage/services', {
      params: { api_key: selectedApiKey.value.api_key }
    })
    availableServices.value = response || []
  } catch (error) {
    console.error('加载服务类型失败:', error)
  }
}

// 移动端设置激活标签
const setActiveTab = (tab: string) => {
  activeTab.value = tab
  showMobileSidebar.value = false
}

// 获取当前标签页标题
const getCurrentTabTitle = () => {
  const titles: Record<string, string> = {
    'keys': 'API密钥',
    'getting-started': '安装Claude Code',
    'packages': '订阅一览',
    'promotion': '推广计划',
    'resources': '资料中心',
    'usage-history': '使用履历'
  }
  return titles[activeTab.value] || '控制台'
}

const refreshUsageRecords = () => {
  loadUsageRecords()
}


const handleUsagePageChange = (page: number) => {
  usagePagination.current = page
  loadUsageRecords()
}

const handleUsageSizeChange = (size: number) => {
  usagePagination.size = size
  usagePagination.current = 1
  loadUsageRecords()
}

// 处理标签页切换
const handleTabChange = (tab: string) => {
  activeTab.value = tab
}

onMounted(() => {
  loadUserKeys()
  loadPlanStatus()

  // 初始化设备检测
  checkDeviceType()

  // 监听窗口大小变化
  window.addEventListener('resize', checkDeviceType)

  // 检查URL参数中的tab参数
  const urlParams = new URLSearchParams(window.location.search)
  const tabParam = urlParams.get('tab')
  if (tabParam && ['keys', 'getting-started', 'packages', 'promotion', 'resources'].includes(tabParam)) {
    activeTab.value = tabParam
  }
})

// 组件卸载时清理事件监听器
onUnmounted(() => {
  window.removeEventListener('resize', checkDeviceType)
})
</script>
