// frontend-react/src/pages/Packages.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import Layout from '@/components/Layout';
import { useUserStore } from '@/store/user';

interface Package {
  id: number;
  package_code: string;
  package_name: string;
  description?: string;
  endpoint?: string;
  price: number;
  credits: number;
  duration_days: number;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

const Packages: React.FC = () => {
  const navigate = useNavigate();
  const { isLoggedIn } = useUserStore();
  const [packages, setPackages] = useState<Package[]>([]);
  const [loading, setLoading] = useState(false);
  const [searchParams, setSearchParams] = useState({
    keyword: '',
    category: '',
    status: ''
  });
  const [selectedPackage, setSelectedPackage] = useState<Package | null>(null);
  const [packageDetailVisible, setPackageDetailVisible] = useState(false);

  // 检查用户认证状态
  useEffect(() => {
    if (!isLoggedIn) {
      navigate('/login');
    }
  }, [isLoggedIn, navigate]);

  // 加载包列表
  const loadPackages = async () => {
    try {
      setLoading(true);
      // TODO: 实现API调用
      // const params = {
      //   keyword: searchParams.keyword || undefined,
      //   category: searchParams.category || undefined,
      //   status: searchParams.status || undefined
      // };
      // const response = await request.get('/api/v1/packages', { params });
      // setPackages(response.packages || []);

      // 模拟数据
      setPackages([
        {
          id: 1,
          package_code: 'basic',
          package_name: '基础套餐',
          description: '适合个人开发者和小团队使用',
          price: 29.9,
          credits: 1000,
          duration_days: 30,
          is_active: true,
          sort_order: 1,
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-01T00:00:00Z'
        },
        {
          id: 2,
          package_code: 'pro',
          package_name: '专业套餐',
          description: '适合中小企业和专业开发者',
          price: 99.9,
          credits: 5000,
          duration_days: 30,
          is_active: true,
          sort_order: 2,
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-01T00:00:00Z'
        },
        {
          id: 3,
          package_code: 'enterprise',
          package_name: '企业套餐',
          description: '适合大型企业和重度用户',
          price: 299.9,
          credits: 20000,
          duration_days: 30,
          is_active: true,
          sort_order: 3,
          created_at: '2024-01-01T00:00:00Z',
          updated_at: '2024-01-01T00:00:00Z'
        }
      ]);
    } catch (error) {
      console.error('加载包列表失败:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isLoggedIn) {
      loadPackages();
    }
  }, [isLoggedIn]);

  const handleSearch = () => {
    loadPackages();
  };

  const handlePackageAction = (pkg: Package) => {
    setSelectedPackage(pkg);
    setPackageDetailVisible(true);
  };

  const handleCloseDetail = () => {
    setPackageDetailVisible(false);
    setSelectedPackage(null);
  };

  const formatDate = (dateString: string) => {
    if (!dateString) return '-';
    return new Date(dateString).toLocaleString('zh-CN');
  };

  const packageCategories = [
    { label: '开发工具', value: 'development' },
    { label: '系统工具', value: 'system' },
    { label: '网络工具', value: 'network' },
    { label: '安全工具', value: 'security' },
    { label: '数据库', value: 'database' },
    { label: '其他', value: 'others' }
  ];

  return (
    <Layout>
      <div className="container mx-auto py-6">
        {/* 页面头部 */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">订阅管理</h1>
              <p className="text-muted-foreground">
                管理和浏览可用的订阅服务
              </p>
            </div>
            <Button onClick={loadPackages} disabled={loading}>
              {loading ? '刷新中...' : '刷新列表'}
            </Button>
          </div>
        </div>

        {/* 搜索和筛选 */}
        <Card className="mb-6">
          <CardContent className="pt-6">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div>
                <Label htmlFor="keyword">搜索</Label>
                <Input
                  id="keyword"
                  placeholder="搜索订阅名称或描述"
                  value={searchParams.keyword}
                  onChange={(e) => setSearchParams({
                    ...searchParams,
                    keyword: e.target.value
                  })}
                  onKeyPress={(e) => {
                    if (e.key === 'Enter') handleSearch();
                  }}
                />
              </div>
              <div>
                <Label htmlFor="category">分类</Label>
                <select
                  id="category"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                  value={searchParams.category}
                  onChange={(e) => setSearchParams({
                    ...searchParams,
                    category: e.target.value
                  })}
                >
                  <option value="">选择分类</option>
                  {packageCategories.map((category) => (
                    <option key={category.value} value={category.value}>
                      {category.label}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <Label htmlFor="status">状态</Label>
                <select
                  id="status"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                  value={searchParams.status}
                  onChange={(e) => setSearchParams({
                    ...searchParams,
                    status: e.target.value
                  })}
                >
                  <option value="">全部</option>
                  <option value="available">可用</option>
                  <option value="unavailable">不可用</option>
                </select>
              </div>
              <div className="flex items-end">
                <Button onClick={handleSearch} className="w-full">
                  搜索
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* 包列表 */}
        <Card>
          <CardHeader>
            <CardTitle>订阅套餐</CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="text-center py-8">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900 mx-auto"></div>
                <p className="mt-2 text-sm text-muted-foreground">加载中...</p>
              </div>
            ) : packages.length === 0 ? (
              <div className="text-center py-8">
                <div className="text-muted-foreground mb-4">
                  <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
                  </svg>
                </div>
                <h3 className="text-lg font-medium text-gray-900 mb-2">暂无订阅数据</h3>
                <p className="text-sm text-muted-foreground">
                  当前没有找到匹配的订阅服务
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {packages.map((pkg) => (
                  <Card key={pkg.id} className="hover:shadow-lg transition-shadow">
                    <CardContent className="p-6">
                      <div className="flex justify-between items-start mb-4">
                        <div>
                          <h3 className="font-semibold text-lg">{pkg.package_name}</h3>
                          <span className="inline-block bg-blue-100 text-blue-800 text-sm px-2 py-1 rounded mt-1">
                            ¥{pkg.price}
                          </span>
                          <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ml-2 ${
                            pkg.is_active
                              ? 'bg-green-100 text-green-800'
                              : 'bg-red-100 text-red-800'
                          }`}>
                            {pkg.is_active ? '可用' : '不可用'}
                          </span>
                        </div>
                      </div>

                      <p className="text-muted-foreground text-sm mb-4">
                        {pkg.description || '暂无描述'}
                      </p>

                      <div className="space-y-2 text-sm text-muted-foreground">
                        <div className="flex justify-between">
                          <span>积分:</span>
                          <span>{pkg.credits}</span>
                        </div>
                        <div className="flex justify-between">
                          <span>时长:</span>
                          <span>{pkg.duration_days} 天</span>
                        </div>
                        <div className="flex justify-between">
                          <span>创建时间:</span>
                          <span>{formatDate(pkg.created_at)}</span>
                        </div>
                      </div>

                      <div className="mt-4">
                        <Button
                          onClick={() => handlePackageAction(pkg)}
                          disabled={!pkg.is_active}
                          className="w-full"
                        >
                          查看详情
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </CardContent>
        </Card>

        {/* 包详情对话框 */}
        {packageDetailVisible && selectedPackage && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
            <Card className="w-full max-w-2xl">
              <CardHeader>
                <CardTitle>包详情</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <strong>订阅名称:</strong>
                    <p>{selectedPackage.package_name}</p>
                  </div>
                  <div>
                    <strong>订阅代码:</strong>
                    <p>{selectedPackage.package_code}</p>
                  </div>
                  <div>
                    <strong>状态:</strong>
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      selectedPackage.is_active
                        ? 'bg-green-100 text-green-800'
                        : 'bg-red-100 text-red-800'
                    }`}>
                      {selectedPackage.is_active ? '可用' : '不可用'}
                    </span>
                  </div>
                  <div>
                    <strong>价格:</strong>
                    <p>¥{selectedPackage.price}</p>
                  </div>
                  <div className="col-span-2">
                    <strong>描述:</strong>
                    <p>{selectedPackage.description || '暂无描述'}</p>
                  </div>
                  <div>
                    <strong>创建时间:</strong>
                    <p>{formatDate(selectedPackage.created_at)}</p>
                  </div>
                  <div>
                    <strong>更新时间:</strong>
                    <p>{formatDate(selectedPackage.updated_at)}</p>
                  </div>
                  <div>
                    <strong>积分:</strong>
                    <p>{selectedPackage.credits}</p>
                  </div>
                  <div>
                    <strong>时长:</strong>
                    <p>{selectedPackage.duration_days} 天</p>
                  </div>
                </div>
              </CardContent>
              <div className="flex justify-end space-x-2 p-6 border-t">
                <Button variant="outline" onClick={handleCloseDetail}>
                  关闭
                </Button>
                {selectedPackage.is_active && (
                  <Button>
                    激活订阅
                  </Button>
                )}
              </div>
            </Card>
          </div>
        )}
      </div>
    </Layout>
  );
};

export default Packages;

// frontend/src/views/Packages.vue
<template>
  <div class="packages-page">
    <div class="container-fluid">
      <!-- 页面头部 -->
      <div class="page-header">
        <div class="row align-items-center">
          <div class="col">
            <h1 class="page-title">
              <i class="fas fa-cube"></i>
              订阅管理
            </h1>
            <p class="page-subtitle">管理和浏览可用的订阅服务</p>
          </div>
          <div class="col-auto">
            <ElButton type="primary" @click="refreshPackages" :loading="loading.list">
              <i class="fas fa-sync-alt"></i>
              刷新列表
            </ElButton>
          </div>
        </div>
      </div>

      <!-- 搜索和筛选 -->
      <div class="filter-section">
        <ElCard shadow="never" class="filter-card">
          <ElRow :gutter="20">
            <ElCol :span="8">
              <ElInput
                v-model="searchParams.keyword"
                placeholder="搜索订阅名称或描述"
                :prefix-icon="ElIconSearch"
                @keyup.enter="handleSearch"
                clearable
              />
            </ElCol>
            <ElCol :span="6">
              <ElSelect
                v-model="searchParams.category"
                placeholder="选择分类"
                clearable
                style="width: 100%"
              >
                <ElOption
                  v-for="category in packageCategories"
                  :key="category.value"
                  :label="category.label"
                  :value="category.value"
                />
              </ElSelect>
            </ElCol>
            <ElCol :span="6">
              <ElSelect
                v-model="searchParams.status"
                placeholder="选择状态"
                clearable
                style="width: 100%"
              >
                <ElOption label="全部" value="" />
                <ElOption label="可用" value="available" />
                <ElOption label="不可用" value="unavailable" />
              </ElSelect>
            </ElCol>
            <ElCol :span="4">
              <ElButton type="primary" @click="handleSearch" style="width: 100%">
                <i class="fas fa-search"></i>
                搜索
              </ElButton>
            </ElCol>
          </ElRow>
        </ElCard>
      </div>

      <!-- 包列表 -->
      <div class="packages-section">
        <ElCard shadow="never" class="packages-card">
          <div v-if="loading.list" class="loading-container">
            <ElSkeleton :rows="5" animated />
          </div>
          <div v-else-if="packages.length === 0" class="empty-state">
            <i class="fas fa-cube empty-icon"></i>
            <h3>暂无订阅数据</h3>
            <p>当前没有找到匹配的订阅服务</p>
          </div>
          <div v-else class="packages-grid">
            <div
              v-for="pkg in packages"
              :key="pkg.id"
              class="package-card"
            >
              <div class="package-header">
                <div class="package-info">
                  <h4 class="package-name">{{ pkg.package_name }}</h4>
                  <span class="package-version">¥{{ pkg.price }}</span>
                  <ElTag
                    :type="pkg.is_active ? 'success' : 'danger'"
                    size="small"
                    class="package-status"
                  >
                    {{ pkg.is_active ? '可用' : '不可用' }}
                  </ElTag>
                </div>
                <div class="package-actions">
                  <ElButton
                    type="primary"
                    size="small"
                    @click="handlePackageAction(pkg)"
                    :disabled="!pkg.is_active"
                  >
                    {{ getUserAction(pkg) }}
                  </ElButton>
                </div>
              </div>
              <div class="package-content">
                <p class="package-description">{{ pkg.description || '暂无描述' }}</p>
                <div class="package-meta">
                  <span class="meta-item">
                    <i class="fas fa-coins"></i>
                    {{ pkg.credits }} 积分
                  </span>
                  <span class="meta-item">
                    <i class="fas fa-calendar"></i>
                    {{ pkg.duration_days }} 天
                  </span>
                  <span class="meta-item">
                    <i class="fas fa-clock"></i>
                    {{ formatDate(pkg.created_at) }}
                  </span>
                </div>
              </div>
            </div>
          </div>

          <!-- 分页 -->
          <div v-if="packages.length > 0" class="pagination-container">
            <ElPagination
              v-model:current-page="pagination.page"
              v-model:page-size="pagination.size"
              :page-sizes="[10, 20, 50, 100]"
              :total="pagination.total"
              layout="total, sizes, prev, pager, next, jumper"
              @size-change="handleSizeChange"
              @current-change="handlePageChange"
            />
          </div>
        </ElCard>
      </div>
    </div>

    <!-- 包详情对话框 -->
    <ElDialog
      v-model="packageDetailVisible"
      title="包详情"
      width="60%"
      :before-close="handleCloseDetail"
    >
      <div v-if="selectedPackage" class="package-detail">
        <ElDescriptions :column="2" border>
          <ElDescriptionsItem label="订阅名称">
            {{ selectedPackage.package_name }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="订阅代码">
            {{ selectedPackage.package_code }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="状态">
            <ElTag :type="selectedPackage.is_active ? 'success' : 'danger'">
              {{ selectedPackage.is_active ? '可用' : '不可用' }}
            </ElTag>
          </ElDescriptionsItem>
          <ElDescriptionsItem label="价格">
            ¥{{ selectedPackage.price }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="描述" :span="2">
            {{ selectedPackage.description || '暂无描述' }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="创建时间">
            {{ formatDate(selectedPackage.created_at) }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="更新时间">
            {{ formatDate(selectedPackage.updated_at) }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="积分">
            {{ selectedPackage.credits }}
          </ElDescriptionsItem>
          <ElDescriptionsItem label="时长">
            {{ selectedPackage.duration_days }} 天
          </ElDescriptionsItem>
        </ElDescriptions>
      </div>
      <template #footer>
        <span class="dialog-footer">
          <ElButton @click="packageDetailVisible = false">关闭</ElButton>
          <ElButton
            v-if="selectedPackage && selectedPackage.is_active"
            type="primary"
            @click="handlePackageAction(selectedPackage)"
          >
            {{ getUserAction(selectedPackage) }}
          </ElButton>
        </span>
      </template>
    </ElDialog>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import {
  ElCard, ElButton, ElInput, ElSelect, ElOption, ElRow, ElCol,
  ElTag, ElSkeleton, ElPagination, ElDialog, ElDescriptions, ElDescriptionsItem
} from 'element-plus'
import { Search as ElIconSearch } from '@element-plus/icons-vue'
import request from '../utils/request'

interface Package {
  id: number
  package_code: string
  package_name: string
  description?: string
  endpoint?: string
  price: number
  credits: number
  duration_days: number
  is_active: boolean
  sort_order: number
  created_at: string
  updated_at: string
}

const router = useRouter()
const packages = ref<Package[]>([])
const selectedPackage = ref<Package | null>(null)
const packageDetailVisible = ref(false)

const loading = reactive({
  list: false,
  action: false
})

const searchParams = reactive({
  keyword: '',
  category: '',
  status: ''
})

const pagination = reactive({
  page: 1,
  size: 20,
  total: 0
})

const packageCategories = [
  { label: '开发工具', value: 'development' },
  { label: '系统工具', value: 'system' },
  { label: '网络工具', value: 'network' },
  { label: '安全工具', value: 'security' },
  { label: '数据库', value: 'database' },
  { label: '其他', value: 'others' }
]

// 加载包列表
const loadPackages = async () => {
  try {
    loading.list = true
    const params = {
      page: pagination.page,
      size: pagination.size,
      keyword: searchParams.keyword || undefined,
      category: searchParams.category || undefined,
      status: searchParams.status || undefined
    }

    const response: any = await request.get('/api/v1/packages', { params })
    packages.value = response.packages || []
    pagination.total = response.total || 0
  } catch (error) {
    console.error('加载包列表失败:', error)
    ElMessage.error('加载包列表失败')
  } finally {
    loading.list = false
  }
}

// 搜索包
const handleSearch = () => {
  pagination.page = 1
  loadPackages()
}

// 刷新包列表
const refreshPackages = () => {
  loadPackages()
}

// 分页处理
const handlePageChange = (page: number) => {
  pagination.page = page
  loadPackages()
}

const handleSizeChange = (size: number) => {
  pagination.size = size
  pagination.page = 1
  loadPackages()
}

// 获取用户对包的操作文本
const getUserAction = (_pkg: Package) => {
  return '查看详情'
}

// 处理包操作
const handlePackageAction = (pkg: Package) => {
  selectedPackage.value = pkg
  packageDetailVisible.value = true
}

// 关闭详情对话框
const handleCloseDetail = () => {
  packageDetailVisible.value = false
  selectedPackage.value = null
}

// 格式化日期
const formatDate = (dateString: string) => {
  if (!dateString) return '-'
  return new Date(dateString).toLocaleString('zh-CN')
}


onMounted(() => {
  loadPackages()
})
</script>

<style scoped>
.packages-page {
  padding: 20px;
  background-color: #f5f7fa;
  min-height: 100vh;
}

.page-header {
  margin-bottom: 24px;
}

.page-title {
  font-size: 2rem;
  font-weight: 600;
  color: #2c3e50;
  margin: 0 0 8px 0;
  display: flex;
  align-items: center;
  gap: 12px;
}

.page-title i {
  color: #409eff;
}

.page-subtitle {
  color: #7f8c8d;
  margin: 0;
  font-size: 1rem;
}

.filter-section {
  margin-bottom: 24px;
}

.filter-card {
  border: none;
  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
}

.packages-section {
  margin-bottom: 24px;
}

.packages-card {
  border: none;
  box-shadow: 0 2px 8px rgba(0,0,0,0.06);
}

.loading-container {
  padding: 20px;
}

.empty-state {
  text-align: center;
  padding: 60px 20px;
  color: #7f8c8d;
}

.empty-icon {
  font-size: 64px;
  color: #ddd;
  margin-bottom: 16px;
}

.packages-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
  gap: 20px;
  padding: 20px;
}

.package-card {
  background: white;
  border: 1px solid #e1e8ed;
  border-radius: 12px;
  padding: 20px;
  transition: all 0.3s ease;
  box-shadow: 0 2px 4px rgba(0,0,0,0.04);
}

.package-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 8px 25px rgba(0,0,0,0.1);
  border-color: #409eff;
}

.package-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 16px;
}

.package-info {
  flex: 1;
}

.package-name {
  font-size: 1.25rem;
  font-weight: 600;
  color: #2c3e50;
  margin: 0 0 8px 0;
}


.package-version {
  display: inline-block;
  background: #ecf5ff;
  color: #409eff;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 0.875rem;
  margin-right: 8px;
}

.package-status {
  margin-left: 8px;
}

.package-actions {
  margin-left: 16px;
}

.package-content {
  margin-top: 16px;
}

.package-description {
  color: #7f8c8d;
  margin: 0 0 16px 0;
  font-size: 0.95rem;
  line-height: 1.5;
}

.package-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
}

.meta-item {
  display: flex;
  align-items: center;
  gap: 6px;
  color: #95a5a6;
  font-size: 0.875rem;
}

.meta-item i {
  color: #bdc3c7;
}

.pagination-container {
  display: flex;
  justify-content: center;
  padding: 20px;
  border-top: 1px solid #f0f2f5;
}

.package-detail {
  margin: 20px 0;
}

/* 移动端适配 */
@media (max-width: 768px) {
  .packages-page {
    padding: 16px;
  }

  .packages-grid {
    grid-template-columns: 1fr;
    padding: 16px;
    gap: 16px;
  }

  .package-header {
    flex-direction: column;
    gap: 12px;
  }

  .package-actions {
    margin-left: 0;
    width: 100%;
  }

  .package-meta {
    gap: 12px;
  }
}

/* 深色主题支持 */
:global(.dark-theme) .packages-page {
  background-color: #0d1117;
}

:global(.dark-theme) .page-title {
  color: #f0f6fc;
}

:global(.dark-theme) .page-subtitle {
  color: #8b949e;
}

:global(.dark-theme) .package-card {
  background: #161b22;
  border-color: #30363d;
}

:global(.dark-theme) .package-name {
  color: #f0f6fc;
}

:global(.dark-theme) .package-description {
  color: #8b949e;
}
</style>
